//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPengguna.SvcMonSatkerManfaatA241 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oracle.com/sca/soapservice/siman_wasdal/monSatkerManfaat/selectManfaatA241" +
        "", ConfigurationName="SvcMonSatkerManfaatA241.execute_ptt")]
    public interface execute_ptt {
        
        // CODEGEN: Generating message contract since the operation execute is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppPengguna.SvcMonSatkerManfaatA241.executeResponse execute(AppPengguna.SvcMonSatkerManfaatA241.executeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="execute", ReplyAction="*")]
        System.IAsyncResult Beginexecute(AppPengguna.SvcMonSatkerManfaatA241.executeRequest request, System.AsyncCallback callback, object asyncState);
        
        AppPengguna.SvcMonSatkerManfaatA241.executeResponse Endexecute(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A241")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> p_MINField;
        
        private bool p_MINFieldSpecified;
        
        private System.Nullable<decimal> p_MAXField;
        
        private bool p_MAXFieldSpecified;
        
        private string sTR_WHEREField;
        
        private string p_COLField;
        
        private string p_SORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> P_MIN {
            get {
                return this.p_MINField;
            }
            set {
                this.p_MINField = value;
                this.RaisePropertyChanged("P_MIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MINSpecified {
            get {
                return this.p_MINFieldSpecified;
            }
            set {
                this.p_MINFieldSpecified = value;
                this.RaisePropertyChanged("P_MINSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> P_MAX {
            get {
                return this.p_MAXField;
            }
            set {
                this.p_MAXField = value;
                this.RaisePropertyChanged("P_MAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MAXSpecified {
            get {
                return this.p_MAXFieldSpecified;
            }
            set {
                this.p_MAXFieldSpecified = value;
                this.RaisePropertyChanged("P_MAXSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string STR_WHERE {
            get {
                return this.sTR_WHEREField;
            }
            set {
                this.sTR_WHEREField = value;
                this.RaisePropertyChanged("STR_WHERE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string P_COL {
            get {
                return this.p_COLField;
            }
            set {
                this.p_COLField = value;
                this.RaisePropertyChanged("P_COL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string P_SORT {
            get {
                return this.p_SORTField;
            }
            set {
                this.p_SORTField = value;
                this.RaisePropertyChanged("P_SORT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WASDAL.SROW_MON_MANFAAT_SATKER_A241", Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A241")]
    public partial class WASDALSROW_MON_MANFAAT_SATKER_A241 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> nUMField;
        
        private bool nUMFieldSpecified;
        
        private System.Nullable<decimal> iD_SK_WASDAL_MANFAATField;
        
        private bool iD_SK_WASDAL_MANFAATFieldSpecified;
        
        private string kD_PELAYANANField;
        
        private System.Nullable<decimal> iD_SATKERField;
        
        private bool iD_SATKERFieldSpecified;
        
        private string kD_SATKERField;
        
        private string uR_SATKERField;
        
        private string sK_KEPUTUSANField;
        
        private System.Nullable<System.DateTime> tGL_SKField;
        
        private bool tGL_SKFieldSpecified;
        
        private string kD_BRGField;
        
        private string uR_SSKELField;
        
        private System.Nullable<decimal> nUPField;
        
        private bool nUPFieldSpecified;
        
        private System.Nullable<decimal> jANGKA_WAKTU_SETUJUField;
        
        private bool jANGKA_WAKTU_SETUJUFieldSpecified;
        
        private string kONTRIBUSI_THNField;
        
        private string nO_BASTField;
        
        private System.Nullable<System.DateTime> tGL_BASTField;
        
        private bool tGL_BASTFieldSpecified;
        
        private string tRANS_SIMAKField;
        
        private string nO_BUKTI_LAKSANAField;
        
        private System.Nullable<System.DateTime> tGL_BUKTI_LAKSANAField;
        
        private bool tGL_BUKTI_LAKSANAFieldSpecified;
        
        private string kD_BRG_TLField;
        
        private string uR_SSKEL_TLField;
        
        private System.Nullable<decimal> nUP_TLField;
        
        private bool nUP_TLFieldSpecified;
        
        private System.Nullable<decimal> kUANTITAS_TLField;
        
        private bool kUANTITAS_TLFieldSpecified;
        
        private System.Nullable<decimal> lUAS_TLField;
        
        private bool lUAS_TLFieldSpecified;
        
        private string nTPNField;
        
        private System.Nullable<System.DateTime> tGL_SETORField;
        
        private bool tGL_SETORFieldSpecified;
        
        private System.Nullable<decimal> nILAI_PNBP_ASETField;
        
        private bool nILAI_PNBP_ASETFieldSpecified;
        
        private string nO_PSPField;
        
        private System.Nullable<System.DateTime> tGL_PSPField;
        
        private bool tGL_PSPFieldSpecified;
        
        private string kESESUAIANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
                this.RaisePropertyChanged("NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUMSpecified {
            get {
                return this.nUMFieldSpecified;
            }
            set {
                this.nUMFieldSpecified = value;
                this.RaisePropertyChanged("NUMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> ID_SK_WASDAL_MANFAAT {
            get {
                return this.iD_SK_WASDAL_MANFAATField;
            }
            set {
                this.iD_SK_WASDAL_MANFAATField = value;
                this.RaisePropertyChanged("ID_SK_WASDAL_MANFAAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SK_WASDAL_MANFAATSpecified {
            get {
                return this.iD_SK_WASDAL_MANFAATFieldSpecified;
            }
            set {
                this.iD_SK_WASDAL_MANFAATFieldSpecified = value;
                this.RaisePropertyChanged("ID_SK_WASDAL_MANFAATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string KD_PELAYANAN {
            get {
                return this.kD_PELAYANANField;
            }
            set {
                this.kD_PELAYANANField = value;
                this.RaisePropertyChanged("KD_PELAYANAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> ID_SATKER {
            get {
                return this.iD_SATKERField;
            }
            set {
                this.iD_SATKERField = value;
                this.RaisePropertyChanged("ID_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SATKERSpecified {
            get {
                return this.iD_SATKERFieldSpecified;
            }
            set {
                this.iD_SATKERFieldSpecified = value;
                this.RaisePropertyChanged("ID_SATKERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string KD_SATKER {
            get {
                return this.kD_SATKERField;
            }
            set {
                this.kD_SATKERField = value;
                this.RaisePropertyChanged("KD_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string UR_SATKER {
            get {
                return this.uR_SATKERField;
            }
            set {
                this.uR_SATKERField = value;
                this.RaisePropertyChanged("UR_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string SK_KEPUTUSAN {
            get {
                return this.sK_KEPUTUSANField;
            }
            set {
                this.sK_KEPUTUSANField = value;
                this.RaisePropertyChanged("SK_KEPUTUSAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> TGL_SK {
            get {
                return this.tGL_SKField;
            }
            set {
                this.tGL_SKField = value;
                this.RaisePropertyChanged("TGL_SK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_SKSpecified {
            get {
                return this.tGL_SKFieldSpecified;
            }
            set {
                this.tGL_SKFieldSpecified = value;
                this.RaisePropertyChanged("TGL_SKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string KD_BRG {
            get {
                return this.kD_BRGField;
            }
            set {
                this.kD_BRGField = value;
                this.RaisePropertyChanged("KD_BRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string UR_SSKEL {
            get {
                return this.uR_SSKELField;
            }
            set {
                this.uR_SSKELField = value;
                this.RaisePropertyChanged("UR_SSKEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> NUP {
            get {
                return this.nUPField;
            }
            set {
                this.nUPField = value;
                this.RaisePropertyChanged("NUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUPSpecified {
            get {
                return this.nUPFieldSpecified;
            }
            set {
                this.nUPFieldSpecified = value;
                this.RaisePropertyChanged("NUPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> JANGKA_WAKTU_SETUJU {
            get {
                return this.jANGKA_WAKTU_SETUJUField;
            }
            set {
                this.jANGKA_WAKTU_SETUJUField = value;
                this.RaisePropertyChanged("JANGKA_WAKTU_SETUJU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JANGKA_WAKTU_SETUJUSpecified {
            get {
                return this.jANGKA_WAKTU_SETUJUFieldSpecified;
            }
            set {
                this.jANGKA_WAKTU_SETUJUFieldSpecified = value;
                this.RaisePropertyChanged("JANGKA_WAKTU_SETUJUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string KONTRIBUSI_THN {
            get {
                return this.kONTRIBUSI_THNField;
            }
            set {
                this.kONTRIBUSI_THNField = value;
                this.RaisePropertyChanged("KONTRIBUSI_THN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string NO_BAST {
            get {
                return this.nO_BASTField;
            }
            set {
                this.nO_BASTField = value;
                this.RaisePropertyChanged("NO_BAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> TGL_BAST {
            get {
                return this.tGL_BASTField;
            }
            set {
                this.tGL_BASTField = value;
                this.RaisePropertyChanged("TGL_BAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_BASTSpecified {
            get {
                return this.tGL_BASTFieldSpecified;
            }
            set {
                this.tGL_BASTFieldSpecified = value;
                this.RaisePropertyChanged("TGL_BASTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string TRANS_SIMAK {
            get {
                return this.tRANS_SIMAKField;
            }
            set {
                this.tRANS_SIMAKField = value;
                this.RaisePropertyChanged("TRANS_SIMAK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string NO_BUKTI_LAKSANA {
            get {
                return this.nO_BUKTI_LAKSANAField;
            }
            set {
                this.nO_BUKTI_LAKSANAField = value;
                this.RaisePropertyChanged("NO_BUKTI_LAKSANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> TGL_BUKTI_LAKSANA {
            get {
                return this.tGL_BUKTI_LAKSANAField;
            }
            set {
                this.tGL_BUKTI_LAKSANAField = value;
                this.RaisePropertyChanged("TGL_BUKTI_LAKSANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_BUKTI_LAKSANASpecified {
            get {
                return this.tGL_BUKTI_LAKSANAFieldSpecified;
            }
            set {
                this.tGL_BUKTI_LAKSANAFieldSpecified = value;
                this.RaisePropertyChanged("TGL_BUKTI_LAKSANASpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string KD_BRG_TL {
            get {
                return this.kD_BRG_TLField;
            }
            set {
                this.kD_BRG_TLField = value;
                this.RaisePropertyChanged("KD_BRG_TL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string UR_SSKEL_TL {
            get {
                return this.uR_SSKEL_TLField;
            }
            set {
                this.uR_SSKEL_TLField = value;
                this.RaisePropertyChanged("UR_SSKEL_TL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<decimal> NUP_TL {
            get {
                return this.nUP_TLField;
            }
            set {
                this.nUP_TLField = value;
                this.RaisePropertyChanged("NUP_TL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUP_TLSpecified {
            get {
                return this.nUP_TLFieldSpecified;
            }
            set {
                this.nUP_TLFieldSpecified = value;
                this.RaisePropertyChanged("NUP_TLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<decimal> KUANTITAS_TL {
            get {
                return this.kUANTITAS_TLField;
            }
            set {
                this.kUANTITAS_TLField = value;
                this.RaisePropertyChanged("KUANTITAS_TL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KUANTITAS_TLSpecified {
            get {
                return this.kUANTITAS_TLFieldSpecified;
            }
            set {
                this.kUANTITAS_TLFieldSpecified = value;
                this.RaisePropertyChanged("KUANTITAS_TLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<decimal> LUAS_TL {
            get {
                return this.lUAS_TLField;
            }
            set {
                this.lUAS_TLField = value;
                this.RaisePropertyChanged("LUAS_TL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LUAS_TLSpecified {
            get {
                return this.lUAS_TLFieldSpecified;
            }
            set {
                this.lUAS_TLFieldSpecified = value;
                this.RaisePropertyChanged("LUAS_TLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string NTPN {
            get {
                return this.nTPNField;
            }
            set {
                this.nTPNField = value;
                this.RaisePropertyChanged("NTPN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> TGL_SETOR {
            get {
                return this.tGL_SETORField;
            }
            set {
                this.tGL_SETORField = value;
                this.RaisePropertyChanged("TGL_SETOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_SETORSpecified {
            get {
                return this.tGL_SETORFieldSpecified;
            }
            set {
                this.tGL_SETORFieldSpecified = value;
                this.RaisePropertyChanged("TGL_SETORSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<decimal> NILAI_PNBP_ASET {
            get {
                return this.nILAI_PNBP_ASETField;
            }
            set {
                this.nILAI_PNBP_ASETField = value;
                this.RaisePropertyChanged("NILAI_PNBP_ASET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NILAI_PNBP_ASETSpecified {
            get {
                return this.nILAI_PNBP_ASETFieldSpecified;
            }
            set {
                this.nILAI_PNBP_ASETFieldSpecified = value;
                this.RaisePropertyChanged("NILAI_PNBP_ASETSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string NO_PSP {
            get {
                return this.nO_PSPField;
            }
            set {
                this.nO_PSPField = value;
                this.RaisePropertyChanged("NO_PSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<System.DateTime> TGL_PSP {
            get {
                return this.tGL_PSPField;
            }
            set {
                this.tGL_PSPField = value;
                this.RaisePropertyChanged("TGL_PSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_PSPSpecified {
            get {
                return this.tGL_PSPFieldSpecified;
            }
            set {
                this.tGL_PSPFieldSpecified = value;
                this.RaisePropertyChanged("TGL_PSPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string KESESUAIAN {
            get {
                return this.kESESUAIANField;
            }
            set {
                this.kESESUAIANField = value;
                this.RaisePropertyChanged("KESESUAIAN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A241")]
    public partial class OutputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WASDALSROW_MON_MANFAAT_SATKER_A241[] sF_MON_MANFAAT_SATKER_A241Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SF_MON_MANFAAT_SATKER_A241_ITEM")]
        public WASDALSROW_MON_MANFAAT_SATKER_A241[] SF_MON_MANFAAT_SATKER_A241 {
            get {
                return this.sF_MON_MANFAAT_SATKER_A241Field;
            }
            set {
                this.sF_MON_MANFAAT_SATKER_A241Field = value;
                this.RaisePropertyChanged("SF_MON_MANFAAT_SATKER_A241");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A241", Order=0)]
        public AppPengguna.SvcMonSatkerManfaatA241.InputParameters InputParameters;
        
        public executeRequest() {
        }
        
        public executeRequest(AppPengguna.SvcMonSatkerManfaatA241.InputParameters InputParameters) {
            this.InputParameters = InputParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A241", Order=0)]
        public AppPengguna.SvcMonSatkerManfaatA241.OutputParameters OutputParameters;
        
        public executeResponse() {
        }
        
        public executeResponse(AppPengguna.SvcMonSatkerManfaatA241.OutputParameters OutputParameters) {
            this.OutputParameters = OutputParameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface execute_pttChannel : AppPengguna.SvcMonSatkerManfaatA241.execute_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class executeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public executeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppPengguna.SvcMonSatkerManfaatA241.OutputParameters Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppPengguna.SvcMonSatkerManfaatA241.OutputParameters)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class execute_pttClient : System.ServiceModel.ClientBase<AppPengguna.SvcMonSatkerManfaatA241.execute_ptt>, AppPengguna.SvcMonSatkerManfaatA241.execute_ptt {
        
        private BeginOperationDelegate onBeginexecuteDelegate;
        
        private EndOperationDelegate onEndexecuteDelegate;
        
        private System.Threading.SendOrPostCallback onexecuteCompletedDelegate;
        
        public execute_pttClient() {
        }
        
        public execute_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public execute_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<executeCompletedEventArgs> executeCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcMonSatkerManfaatA241.executeResponse AppPengguna.SvcMonSatkerManfaatA241.execute_ptt.execute(AppPengguna.SvcMonSatkerManfaatA241.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public AppPengguna.SvcMonSatkerManfaatA241.OutputParameters execute(AppPengguna.SvcMonSatkerManfaatA241.InputParameters InputParameters) {
            AppPengguna.SvcMonSatkerManfaatA241.executeRequest inValue = new AppPengguna.SvcMonSatkerManfaatA241.executeRequest();
            inValue.InputParameters = InputParameters;
            AppPengguna.SvcMonSatkerManfaatA241.executeResponse retVal = ((AppPengguna.SvcMonSatkerManfaatA241.execute_ptt)(this)).execute(inValue);
            return retVal.OutputParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppPengguna.SvcMonSatkerManfaatA241.execute_ptt.Beginexecute(AppPengguna.SvcMonSatkerManfaatA241.executeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginexecute(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginexecute(AppPengguna.SvcMonSatkerManfaatA241.InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcMonSatkerManfaatA241.executeRequest inValue = new AppPengguna.SvcMonSatkerManfaatA241.executeRequest();
            inValue.InputParameters = InputParameters;
            return ((AppPengguna.SvcMonSatkerManfaatA241.execute_ptt)(this)).Beginexecute(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcMonSatkerManfaatA241.executeResponse AppPengguna.SvcMonSatkerManfaatA241.execute_ptt.Endexecute(System.IAsyncResult result) {
            return base.Channel.Endexecute(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppPengguna.SvcMonSatkerManfaatA241.OutputParameters Endexecute(System.IAsyncResult result) {
            AppPengguna.SvcMonSatkerManfaatA241.executeResponse retVal = ((AppPengguna.SvcMonSatkerManfaatA241.execute_ptt)(this)).Endexecute(result);
            return retVal.OutputParameters;
        }
        
        private System.IAsyncResult OnBeginexecute(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcMonSatkerManfaatA241.InputParameters InputParameters = ((AppPengguna.SvcMonSatkerManfaatA241.InputParameters)(inValues[0]));
            return this.Beginexecute(InputParameters, callback, asyncState);
        }
        
        private object[] OnEndexecute(System.IAsyncResult result) {
            AppPengguna.SvcMonSatkerManfaatA241.OutputParameters retVal = this.Endexecute(result);
            return new object[] {
                    retVal};
        }
        
        private void OnexecuteCompleted(object state) {
            if ((this.executeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.executeCompleted(this, new executeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void executeAsync(AppPengguna.SvcMonSatkerManfaatA241.InputParameters InputParameters) {
            this.executeAsync(InputParameters, null);
        }
        
        public void executeAsync(AppPengguna.SvcMonSatkerManfaatA241.InputParameters InputParameters, object userState) {
            if ((this.onBeginexecuteDelegate == null)) {
                this.onBeginexecuteDelegate = new BeginOperationDelegate(this.OnBeginexecute);
            }
            if ((this.onEndexecuteDelegate == null)) {
                this.onEndexecuteDelegate = new EndOperationDelegate(this.OnEndexecute);
            }
            if ((this.onexecuteCompletedDelegate == null)) {
                this.onexecuteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnexecuteCompleted);
            }
            base.InvokeAsync(this.onBeginexecuteDelegate, new object[] {
                        InputParameters}, this.onEndexecuteDelegate, this.onexecuteCompletedDelegate, userState);
        }
    }
}
