//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPengguna.SvcMonSatkerManfaatA221 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oracle.com/sca/soapservice/siman_wasdal/monSatkerManfaat/selectManfaatA221" +
        "", ConfigurationName="SvcMonSatkerManfaatA221.execute_ptt")]
    public interface execute_ptt {
        
        // CODEGEN: Generating message contract since the operation execute is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppPengguna.SvcMonSatkerManfaatA221.executeResponse execute(AppPengguna.SvcMonSatkerManfaatA221.executeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="execute", ReplyAction="*")]
        System.IAsyncResult Beginexecute(AppPengguna.SvcMonSatkerManfaatA221.executeRequest request, System.AsyncCallback callback, object asyncState);
        
        AppPengguna.SvcMonSatkerManfaatA221.executeResponse Endexecute(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A221")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> p_MINField;
        
        private bool p_MINFieldSpecified;
        
        private System.Nullable<decimal> p_MAXField;
        
        private bool p_MAXFieldSpecified;
        
        private string sTR_WHEREField;
        
        private string p_COLField;
        
        private string p_SORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> P_MIN {
            get {
                return this.p_MINField;
            }
            set {
                this.p_MINField = value;
                this.RaisePropertyChanged("P_MIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MINSpecified {
            get {
                return this.p_MINFieldSpecified;
            }
            set {
                this.p_MINFieldSpecified = value;
                this.RaisePropertyChanged("P_MINSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> P_MAX {
            get {
                return this.p_MAXField;
            }
            set {
                this.p_MAXField = value;
                this.RaisePropertyChanged("P_MAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MAXSpecified {
            get {
                return this.p_MAXFieldSpecified;
            }
            set {
                this.p_MAXFieldSpecified = value;
                this.RaisePropertyChanged("P_MAXSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string STR_WHERE {
            get {
                return this.sTR_WHEREField;
            }
            set {
                this.sTR_WHEREField = value;
                this.RaisePropertyChanged("STR_WHERE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string P_COL {
            get {
                return this.p_COLField;
            }
            set {
                this.p_COLField = value;
                this.RaisePropertyChanged("P_COL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string P_SORT {
            get {
                return this.p_SORTField;
            }
            set {
                this.p_SORTField = value;
                this.RaisePropertyChanged("P_SORT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WASDAL.SROW_MON_MANFAAT_SATKER_A221", Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A221")]
    public partial class WASDALSROW_MON_MANFAAT_SATKER_A221 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> nUMField;
        
        private bool nUMFieldSpecified;
        
        private System.Nullable<decimal> iD_SK_WASDAL_MANFAATField;
        
        private bool iD_SK_WASDAL_MANFAATFieldSpecified;
        
        private System.Nullable<decimal> iD_SATKERField;
        
        private bool iD_SATKERFieldSpecified;
        
        private string kD_SATKERField;
        
        private string uR_SATKERField;
        
        private string sK_KEPUTUSANField;
        
        private System.Nullable<System.DateTime> tGL_SKField;
        
        private bool tGL_SKFieldSpecified;
        
        private string kD_BRGField;
        
        private string uR_SSKELField;
        
        private System.Nullable<decimal> nUPField;
        
        private bool nUPFieldSpecified;
        
        private string pEMINJAMField;
        
        private System.Nullable<decimal> jANGKA_WAKTU_SETUJUField;
        
        private bool jANGKA_WAKTU_SETUJUFieldSpecified;
        
        private string pERIODE_SETUJUField;
        
        private System.Nullable<System.DateTime> dARI_TGL_SETUJUField;
        
        private bool dARI_TGL_SETUJUFieldSpecified;
        
        private System.Nullable<System.DateTime> sD_TGL_SETUJUField;
        
        private bool sD_TGL_SETUJUFieldSpecified;
        
        private System.Nullable<decimal> nILAI_PERSETUJUANField;
        
        private bool nILAI_PERSETUJUANFieldSpecified;
        
        private string nO_REKAM_PERJANJIANField;
        
        private System.Nullable<System.DateTime> tGL_REKAM_PERJANJIANField;
        
        private bool tGL_REKAM_PERJANJIANFieldSpecified;
        
        private System.Nullable<decimal> jANGKA_WAKTU_JANJIField;
        
        private bool jANGKA_WAKTU_JANJIFieldSpecified;
        
        private System.Nullable<decimal> sISA_WAKTU_JANJIField;
        
        private bool sISA_WAKTU_JANJIFieldSpecified;
        
        private string pERIODE_JANJIField;
        
        private System.Nullable<decimal> nILAI_PERSETUJUAN_JANJIField;
        
        private bool nILAI_PERSETUJUAN_JANJIFieldSpecified;
        
        private System.Nullable<decimal> nILAI_PNBP_ASETField;
        
        private bool nILAI_PNBP_ASETFieldSpecified;
        
        private string nO_BUKTI_LAKSANAField;
        
        private System.Nullable<System.DateTime> tGL_BUKTI_LAKSANAField;
        
        private bool tGL_BUKTI_LAKSANAFieldSpecified;
        
        private System.Nullable<decimal> sISA_WAKTUField;
        
        private bool sISA_WAKTUFieldSpecified;
        
        private string sTATUS_PERJANJIANField;
        
        private string nO_BASTField;
        
        private System.Nullable<System.DateTime> tGL_BASTField;
        
        private bool tGL_BASTFieldSpecified;
        
        private string nO_LAP_AKHIRField;
        
        private System.Nullable<System.DateTime> tGL_LAP_AKHIRField;
        
        private bool tGL_LAP_AKHIRFieldSpecified;
        
        private string kESESUAIANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
                this.RaisePropertyChanged("NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUMSpecified {
            get {
                return this.nUMFieldSpecified;
            }
            set {
                this.nUMFieldSpecified = value;
                this.RaisePropertyChanged("NUMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> ID_SK_WASDAL_MANFAAT {
            get {
                return this.iD_SK_WASDAL_MANFAATField;
            }
            set {
                this.iD_SK_WASDAL_MANFAATField = value;
                this.RaisePropertyChanged("ID_SK_WASDAL_MANFAAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SK_WASDAL_MANFAATSpecified {
            get {
                return this.iD_SK_WASDAL_MANFAATFieldSpecified;
            }
            set {
                this.iD_SK_WASDAL_MANFAATFieldSpecified = value;
                this.RaisePropertyChanged("ID_SK_WASDAL_MANFAATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> ID_SATKER {
            get {
                return this.iD_SATKERField;
            }
            set {
                this.iD_SATKERField = value;
                this.RaisePropertyChanged("ID_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SATKERSpecified {
            get {
                return this.iD_SATKERFieldSpecified;
            }
            set {
                this.iD_SATKERFieldSpecified = value;
                this.RaisePropertyChanged("ID_SATKERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string KD_SATKER {
            get {
                return this.kD_SATKERField;
            }
            set {
                this.kD_SATKERField = value;
                this.RaisePropertyChanged("KD_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string UR_SATKER {
            get {
                return this.uR_SATKERField;
            }
            set {
                this.uR_SATKERField = value;
                this.RaisePropertyChanged("UR_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string SK_KEPUTUSAN {
            get {
                return this.sK_KEPUTUSANField;
            }
            set {
                this.sK_KEPUTUSANField = value;
                this.RaisePropertyChanged("SK_KEPUTUSAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> TGL_SK {
            get {
                return this.tGL_SKField;
            }
            set {
                this.tGL_SKField = value;
                this.RaisePropertyChanged("TGL_SK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_SKSpecified {
            get {
                return this.tGL_SKFieldSpecified;
            }
            set {
                this.tGL_SKFieldSpecified = value;
                this.RaisePropertyChanged("TGL_SKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string KD_BRG {
            get {
                return this.kD_BRGField;
            }
            set {
                this.kD_BRGField = value;
                this.RaisePropertyChanged("KD_BRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string UR_SSKEL {
            get {
                return this.uR_SSKELField;
            }
            set {
                this.uR_SSKELField = value;
                this.RaisePropertyChanged("UR_SSKEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> NUP {
            get {
                return this.nUPField;
            }
            set {
                this.nUPField = value;
                this.RaisePropertyChanged("NUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUPSpecified {
            get {
                return this.nUPFieldSpecified;
            }
            set {
                this.nUPFieldSpecified = value;
                this.RaisePropertyChanged("NUPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string PEMINJAM {
            get {
                return this.pEMINJAMField;
            }
            set {
                this.pEMINJAMField = value;
                this.RaisePropertyChanged("PEMINJAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> JANGKA_WAKTU_SETUJU {
            get {
                return this.jANGKA_WAKTU_SETUJUField;
            }
            set {
                this.jANGKA_WAKTU_SETUJUField = value;
                this.RaisePropertyChanged("JANGKA_WAKTU_SETUJU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JANGKA_WAKTU_SETUJUSpecified {
            get {
                return this.jANGKA_WAKTU_SETUJUFieldSpecified;
            }
            set {
                this.jANGKA_WAKTU_SETUJUFieldSpecified = value;
                this.RaisePropertyChanged("JANGKA_WAKTU_SETUJUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string PERIODE_SETUJU {
            get {
                return this.pERIODE_SETUJUField;
            }
            set {
                this.pERIODE_SETUJUField = value;
                this.RaisePropertyChanged("PERIODE_SETUJU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> DARI_TGL_SETUJU {
            get {
                return this.dARI_TGL_SETUJUField;
            }
            set {
                this.dARI_TGL_SETUJUField = value;
                this.RaisePropertyChanged("DARI_TGL_SETUJU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DARI_TGL_SETUJUSpecified {
            get {
                return this.dARI_TGL_SETUJUFieldSpecified;
            }
            set {
                this.dARI_TGL_SETUJUFieldSpecified = value;
                this.RaisePropertyChanged("DARI_TGL_SETUJUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> SD_TGL_SETUJU {
            get {
                return this.sD_TGL_SETUJUField;
            }
            set {
                this.sD_TGL_SETUJUField = value;
                this.RaisePropertyChanged("SD_TGL_SETUJU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SD_TGL_SETUJUSpecified {
            get {
                return this.sD_TGL_SETUJUFieldSpecified;
            }
            set {
                this.sD_TGL_SETUJUFieldSpecified = value;
                this.RaisePropertyChanged("SD_TGL_SETUJUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> NILAI_PERSETUJUAN {
            get {
                return this.nILAI_PERSETUJUANField;
            }
            set {
                this.nILAI_PERSETUJUANField = value;
                this.RaisePropertyChanged("NILAI_PERSETUJUAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NILAI_PERSETUJUANSpecified {
            get {
                return this.nILAI_PERSETUJUANFieldSpecified;
            }
            set {
                this.nILAI_PERSETUJUANFieldSpecified = value;
                this.RaisePropertyChanged("NILAI_PERSETUJUANSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string NO_REKAM_PERJANJIAN {
            get {
                return this.nO_REKAM_PERJANJIANField;
            }
            set {
                this.nO_REKAM_PERJANJIANField = value;
                this.RaisePropertyChanged("NO_REKAM_PERJANJIAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> TGL_REKAM_PERJANJIAN {
            get {
                return this.tGL_REKAM_PERJANJIANField;
            }
            set {
                this.tGL_REKAM_PERJANJIANField = value;
                this.RaisePropertyChanged("TGL_REKAM_PERJANJIAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_REKAM_PERJANJIANSpecified {
            get {
                return this.tGL_REKAM_PERJANJIANFieldSpecified;
            }
            set {
                this.tGL_REKAM_PERJANJIANFieldSpecified = value;
                this.RaisePropertyChanged("TGL_REKAM_PERJANJIANSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<decimal> JANGKA_WAKTU_JANJI {
            get {
                return this.jANGKA_WAKTU_JANJIField;
            }
            set {
                this.jANGKA_WAKTU_JANJIField = value;
                this.RaisePropertyChanged("JANGKA_WAKTU_JANJI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JANGKA_WAKTU_JANJISpecified {
            get {
                return this.jANGKA_WAKTU_JANJIFieldSpecified;
            }
            set {
                this.jANGKA_WAKTU_JANJIFieldSpecified = value;
                this.RaisePropertyChanged("JANGKA_WAKTU_JANJISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> SISA_WAKTU_JANJI {
            get {
                return this.sISA_WAKTU_JANJIField;
            }
            set {
                this.sISA_WAKTU_JANJIField = value;
                this.RaisePropertyChanged("SISA_WAKTU_JANJI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SISA_WAKTU_JANJISpecified {
            get {
                return this.sISA_WAKTU_JANJIFieldSpecified;
            }
            set {
                this.sISA_WAKTU_JANJIFieldSpecified = value;
                this.RaisePropertyChanged("SISA_WAKTU_JANJISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string PERIODE_JANJI {
            get {
                return this.pERIODE_JANJIField;
            }
            set {
                this.pERIODE_JANJIField = value;
                this.RaisePropertyChanged("PERIODE_JANJI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<decimal> NILAI_PERSETUJUAN_JANJI {
            get {
                return this.nILAI_PERSETUJUAN_JANJIField;
            }
            set {
                this.nILAI_PERSETUJUAN_JANJIField = value;
                this.RaisePropertyChanged("NILAI_PERSETUJUAN_JANJI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NILAI_PERSETUJUAN_JANJISpecified {
            get {
                return this.nILAI_PERSETUJUAN_JANJIFieldSpecified;
            }
            set {
                this.nILAI_PERSETUJUAN_JANJIFieldSpecified = value;
                this.RaisePropertyChanged("NILAI_PERSETUJUAN_JANJISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<decimal> NILAI_PNBP_ASET {
            get {
                return this.nILAI_PNBP_ASETField;
            }
            set {
                this.nILAI_PNBP_ASETField = value;
                this.RaisePropertyChanged("NILAI_PNBP_ASET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NILAI_PNBP_ASETSpecified {
            get {
                return this.nILAI_PNBP_ASETFieldSpecified;
            }
            set {
                this.nILAI_PNBP_ASETFieldSpecified = value;
                this.RaisePropertyChanged("NILAI_PNBP_ASETSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string NO_BUKTI_LAKSANA {
            get {
                return this.nO_BUKTI_LAKSANAField;
            }
            set {
                this.nO_BUKTI_LAKSANAField = value;
                this.RaisePropertyChanged("NO_BUKTI_LAKSANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> TGL_BUKTI_LAKSANA {
            get {
                return this.tGL_BUKTI_LAKSANAField;
            }
            set {
                this.tGL_BUKTI_LAKSANAField = value;
                this.RaisePropertyChanged("TGL_BUKTI_LAKSANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_BUKTI_LAKSANASpecified {
            get {
                return this.tGL_BUKTI_LAKSANAFieldSpecified;
            }
            set {
                this.tGL_BUKTI_LAKSANAFieldSpecified = value;
                this.RaisePropertyChanged("TGL_BUKTI_LAKSANASpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<decimal> SISA_WAKTU {
            get {
                return this.sISA_WAKTUField;
            }
            set {
                this.sISA_WAKTUField = value;
                this.RaisePropertyChanged("SISA_WAKTU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SISA_WAKTUSpecified {
            get {
                return this.sISA_WAKTUFieldSpecified;
            }
            set {
                this.sISA_WAKTUFieldSpecified = value;
                this.RaisePropertyChanged("SISA_WAKTUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string STATUS_PERJANJIAN {
            get {
                return this.sTATUS_PERJANJIANField;
            }
            set {
                this.sTATUS_PERJANJIANField = value;
                this.RaisePropertyChanged("STATUS_PERJANJIAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string NO_BAST {
            get {
                return this.nO_BASTField;
            }
            set {
                this.nO_BASTField = value;
                this.RaisePropertyChanged("NO_BAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<System.DateTime> TGL_BAST {
            get {
                return this.tGL_BASTField;
            }
            set {
                this.tGL_BASTField = value;
                this.RaisePropertyChanged("TGL_BAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_BASTSpecified {
            get {
                return this.tGL_BASTFieldSpecified;
            }
            set {
                this.tGL_BASTFieldSpecified = value;
                this.RaisePropertyChanged("TGL_BASTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string NO_LAP_AKHIR {
            get {
                return this.nO_LAP_AKHIRField;
            }
            set {
                this.nO_LAP_AKHIRField = value;
                this.RaisePropertyChanged("NO_LAP_AKHIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<System.DateTime> TGL_LAP_AKHIR {
            get {
                return this.tGL_LAP_AKHIRField;
            }
            set {
                this.tGL_LAP_AKHIRField = value;
                this.RaisePropertyChanged("TGL_LAP_AKHIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_LAP_AKHIRSpecified {
            get {
                return this.tGL_LAP_AKHIRFieldSpecified;
            }
            set {
                this.tGL_LAP_AKHIRFieldSpecified = value;
                this.RaisePropertyChanged("TGL_LAP_AKHIRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string KESESUAIAN {
            get {
                return this.kESESUAIANField;
            }
            set {
                this.kESESUAIANField = value;
                this.RaisePropertyChanged("KESESUAIAN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A221")]
    public partial class OutputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WASDALSROW_MON_MANFAAT_SATKER_A221[] sF_MON_MANFAAT_SATKER_A221Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SF_MON_MANFAAT_SATKER_A221_ITEM")]
        public WASDALSROW_MON_MANFAAT_SATKER_A221[] SF_MON_MANFAAT_SATKER_A221 {
            get {
                return this.sF_MON_MANFAAT_SATKER_A221Field;
            }
            set {
                this.sF_MON_MANFAAT_SATKER_A221Field = value;
                this.RaisePropertyChanged("SF_MON_MANFAAT_SATKER_A221");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A221", Order=0)]
        public AppPengguna.SvcMonSatkerManfaatA221.InputParameters InputParameters;
        
        public executeRequest() {
        }
        
        public executeRequest(AppPengguna.SvcMonSatkerManfaatA221.InputParameters InputParameters) {
            this.InputParameters = InputParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_MANFAAT_SATKER_A221", Order=0)]
        public AppPengguna.SvcMonSatkerManfaatA221.OutputParameters OutputParameters;
        
        public executeResponse() {
        }
        
        public executeResponse(AppPengguna.SvcMonSatkerManfaatA221.OutputParameters OutputParameters) {
            this.OutputParameters = OutputParameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface execute_pttChannel : AppPengguna.SvcMonSatkerManfaatA221.execute_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class executeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public executeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppPengguna.SvcMonSatkerManfaatA221.OutputParameters Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppPengguna.SvcMonSatkerManfaatA221.OutputParameters)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class execute_pttClient : System.ServiceModel.ClientBase<AppPengguna.SvcMonSatkerManfaatA221.execute_ptt>, AppPengguna.SvcMonSatkerManfaatA221.execute_ptt {
        
        private BeginOperationDelegate onBeginexecuteDelegate;
        
        private EndOperationDelegate onEndexecuteDelegate;
        
        private System.Threading.SendOrPostCallback onexecuteCompletedDelegate;
        
        public execute_pttClient() {
        }
        
        public execute_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public execute_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<executeCompletedEventArgs> executeCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcMonSatkerManfaatA221.executeResponse AppPengguna.SvcMonSatkerManfaatA221.execute_ptt.execute(AppPengguna.SvcMonSatkerManfaatA221.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public AppPengguna.SvcMonSatkerManfaatA221.OutputParameters execute(AppPengguna.SvcMonSatkerManfaatA221.InputParameters InputParameters) {
            AppPengguna.SvcMonSatkerManfaatA221.executeRequest inValue = new AppPengguna.SvcMonSatkerManfaatA221.executeRequest();
            inValue.InputParameters = InputParameters;
            AppPengguna.SvcMonSatkerManfaatA221.executeResponse retVal = ((AppPengguna.SvcMonSatkerManfaatA221.execute_ptt)(this)).execute(inValue);
            return retVal.OutputParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppPengguna.SvcMonSatkerManfaatA221.execute_ptt.Beginexecute(AppPengguna.SvcMonSatkerManfaatA221.executeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginexecute(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginexecute(AppPengguna.SvcMonSatkerManfaatA221.InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcMonSatkerManfaatA221.executeRequest inValue = new AppPengguna.SvcMonSatkerManfaatA221.executeRequest();
            inValue.InputParameters = InputParameters;
            return ((AppPengguna.SvcMonSatkerManfaatA221.execute_ptt)(this)).Beginexecute(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcMonSatkerManfaatA221.executeResponse AppPengguna.SvcMonSatkerManfaatA221.execute_ptt.Endexecute(System.IAsyncResult result) {
            return base.Channel.Endexecute(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppPengguna.SvcMonSatkerManfaatA221.OutputParameters Endexecute(System.IAsyncResult result) {
            AppPengguna.SvcMonSatkerManfaatA221.executeResponse retVal = ((AppPengguna.SvcMonSatkerManfaatA221.execute_ptt)(this)).Endexecute(result);
            return retVal.OutputParameters;
        }
        
        private System.IAsyncResult OnBeginexecute(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcMonSatkerManfaatA221.InputParameters InputParameters = ((AppPengguna.SvcMonSatkerManfaatA221.InputParameters)(inValues[0]));
            return this.Beginexecute(InputParameters, callback, asyncState);
        }
        
        private object[] OnEndexecute(System.IAsyncResult result) {
            AppPengguna.SvcMonSatkerManfaatA221.OutputParameters retVal = this.Endexecute(result);
            return new object[] {
                    retVal};
        }
        
        private void OnexecuteCompleted(object state) {
            if ((this.executeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.executeCompleted(this, new executeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void executeAsync(AppPengguna.SvcMonSatkerManfaatA221.InputParameters InputParameters) {
            this.executeAsync(InputParameters, null);
        }
        
        public void executeAsync(AppPengguna.SvcMonSatkerManfaatA221.InputParameters InputParameters, object userState) {
            if ((this.onBeginexecuteDelegate == null)) {
                this.onBeginexecuteDelegate = new BeginOperationDelegate(this.OnBeginexecute);
            }
            if ((this.onEndexecuteDelegate == null)) {
                this.onEndexecuteDelegate = new EndOperationDelegate(this.OnEndexecute);
            }
            if ((this.onexecuteCompletedDelegate == null)) {
                this.onexecuteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnexecuteCompleted);
            }
            base.InvokeAsync(this.onBeginexecuteDelegate, new object[] {
                        InputParameters}, this.onEndexecuteDelegate, this.onexecuteCompletedDelegate, userState);
        }
    }
}
