//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPengguna.SvcSelectGunaB51 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oracle.com/sca/soapservice/siman_wasdal/wasdalMonKpknl/selectGunaB51", ConfigurationName="SvcSelectGunaB51.execute_ptt")]
    public interface execute_ptt {
        
        // CODEGEN: Generating message contract since the operation execute is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppPengguna.SvcSelectGunaB51.executeResponse execute(AppPengguna.SvcSelectGunaB51.executeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="execute", ReplyAction="*")]
        System.IAsyncResult Beginexecute(AppPengguna.SvcSelectGunaB51.executeRequest request, System.AsyncCallback callback, object asyncState);
        
        AppPengguna.SvcSelectGunaB51.executeResponse Endexecute(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_GUNA_KPKNL_B51")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> p_MINField;
        
        private bool p_MINFieldSpecified;
        
        private System.Nullable<decimal> p_MAXField;
        
        private bool p_MAXFieldSpecified;
        
        private string sTR_WHEREField;
        
        private string p_COLField;
        
        private string p_SORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> P_MIN {
            get {
                return this.p_MINField;
            }
            set {
                this.p_MINField = value;
                this.RaisePropertyChanged("P_MIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MINSpecified {
            get {
                return this.p_MINFieldSpecified;
            }
            set {
                this.p_MINFieldSpecified = value;
                this.RaisePropertyChanged("P_MINSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> P_MAX {
            get {
                return this.p_MAXField;
            }
            set {
                this.p_MAXField = value;
                this.RaisePropertyChanged("P_MAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MAXSpecified {
            get {
                return this.p_MAXFieldSpecified;
            }
            set {
                this.p_MAXFieldSpecified = value;
                this.RaisePropertyChanged("P_MAXSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string STR_WHERE {
            get {
                return this.sTR_WHEREField;
            }
            set {
                this.sTR_WHEREField = value;
                this.RaisePropertyChanged("STR_WHERE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string P_COL {
            get {
                return this.p_COLField;
            }
            set {
                this.p_COLField = value;
                this.RaisePropertyChanged("P_COL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string P_SORT {
            get {
                return this.p_SORTField;
            }
            set {
                this.p_SORTField = value;
                this.RaisePropertyChanged("P_SORT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WASDAL.SROW_MON_GUNA_KPKNL_B51", Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_GUNA_KPKNL_B51")]
    public partial class WASDALSROW_MON_GUNA_KPKNL_B51 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> nUMField;
        
        private bool nUMFieldSpecified;
        
        private System.Nullable<decimal> iD_ASETField;
        
        private bool iD_ASETFieldSpecified;
        
        private System.Nullable<decimal> kD_JNS_BMNField;
        
        private bool kD_JNS_BMNFieldSpecified;
        
        private string kD_BRGField;
        
        private string uR_SSKELField;
        
        private System.Nullable<decimal> nUPField;
        
        private bool nUPFieldSpecified;
        
        private System.Nullable<decimal> lUASField;
        
        private bool lUASFieldSpecified;
        
        private System.Nullable<decimal> nIL_PERLHField;
        
        private bool nIL_PERLHFieldSpecified;
        
        private System.Nullable<decimal> iD_SATKERField;
        
        private bool iD_SATKERFieldSpecified;
        
        private string tINGKAT_PERKARA_TK1Field;
        
        private string jNS_PERKARA_TK1Field;
        
        private string nM_PENGADILAN_TK1Field;
        
        private string nO_PERKARA_TK1NO_PERKARAField;
        
        private System.Nullable<System.DateTime> tGL_SENGKETA_TK1Field;
        
        private bool tGL_SENGKETA_TK1FieldSpecified;
        
        private string pIHAK_PENGGUGAT_TK1Field;
        
        private string pIHAK_TERGUGAT_TK1Field;
        
        private string aMAR_PUTUSAN_TK1Field;
        
        private string pOKOK_PERKARA_TK1Field;
        
        private string tINGKAT_PERKARA_TK_TGIField;
        
        private string jNS_PERKARA_TK_TGIField;
        
        private string nM_PENGADILAN_TK_TGIField;
        
        private string nO_PERKARA_TK_TGIField;
        
        private System.Nullable<System.DateTime> tGL_SENGKETA_TK_TGIField;
        
        private bool tGL_SENGKETA_TK_TGIFieldSpecified;
        
        private string pIHAK_PENGGUGAT_TK_TGIField;
        
        private string pIHAK_TERGUGAT_TK_TGIField;
        
        private string aMAR_PUTUSAN_TK_TGIField;
        
        private string pOKOK_PERKARA_TK_TGIField;
        
        private string tINGKAT_PERKARA_TK_KSIField;
        
        private string jNS_PERKARA_TK_KSIField;
        
        private string nM_PENGADILAN_TK_KSIField;
        
        private string nO_PERKARA_TK_KSIField;
        
        private System.Nullable<System.DateTime> tGL_SENGKETA_TK_KSIField;
        
        private bool tGL_SENGKETA_TK_KSIFieldSpecified;
        
        private string pIHAK_PENGGUGAT_TK_KSIField;
        
        private string pIHAK_TERGUGAT_TK_KSIField;
        
        private string aMAR_PUTUSAN_TK_KSIField;
        
        private string pOKOK_PERKARA_TK_KSIField;
        
        private string tINGKAT_PERKARA_TK_PKField;
        
        private string jNS_PERKARA_TK_PKField;
        
        private string nM_PENGADILAN_TK_PKField;
        
        private string nO_PERKARA_TK_PKField;
        
        private System.Nullable<System.DateTime> tGL_SENGKETA_TK_PKField;
        
        private bool tGL_SENGKETA_TK_PKFieldSpecified;
        
        private string pIHAK_PENGGUGAT_TK_PKField;
        
        private string pIHAK_TERGUGAT_TK_PKField;
        
        private string aMAR_PUTUSAN_TK_PKField;
        
        private string pOKOK_PERKARA_TK_PKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
                this.RaisePropertyChanged("NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUMSpecified {
            get {
                return this.nUMFieldSpecified;
            }
            set {
                this.nUMFieldSpecified = value;
                this.RaisePropertyChanged("NUMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> ID_ASET {
            get {
                return this.iD_ASETField;
            }
            set {
                this.iD_ASETField = value;
                this.RaisePropertyChanged("ID_ASET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_ASETSpecified {
            get {
                return this.iD_ASETFieldSpecified;
            }
            set {
                this.iD_ASETFieldSpecified = value;
                this.RaisePropertyChanged("ID_ASETSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> KD_JNS_BMN {
            get {
                return this.kD_JNS_BMNField;
            }
            set {
                this.kD_JNS_BMNField = value;
                this.RaisePropertyChanged("KD_JNS_BMN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KD_JNS_BMNSpecified {
            get {
                return this.kD_JNS_BMNFieldSpecified;
            }
            set {
                this.kD_JNS_BMNFieldSpecified = value;
                this.RaisePropertyChanged("KD_JNS_BMNSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string KD_BRG {
            get {
                return this.kD_BRGField;
            }
            set {
                this.kD_BRGField = value;
                this.RaisePropertyChanged("KD_BRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string UR_SSKEL {
            get {
                return this.uR_SSKELField;
            }
            set {
                this.uR_SSKELField = value;
                this.RaisePropertyChanged("UR_SSKEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> NUP {
            get {
                return this.nUPField;
            }
            set {
                this.nUPField = value;
                this.RaisePropertyChanged("NUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUPSpecified {
            get {
                return this.nUPFieldSpecified;
            }
            set {
                this.nUPFieldSpecified = value;
                this.RaisePropertyChanged("NUPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> LUAS {
            get {
                return this.lUASField;
            }
            set {
                this.lUASField = value;
                this.RaisePropertyChanged("LUAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LUASSpecified {
            get {
                return this.lUASFieldSpecified;
            }
            set {
                this.lUASFieldSpecified = value;
                this.RaisePropertyChanged("LUASSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> NIL_PERLH {
            get {
                return this.nIL_PERLHField;
            }
            set {
                this.nIL_PERLHField = value;
                this.RaisePropertyChanged("NIL_PERLH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NIL_PERLHSpecified {
            get {
                return this.nIL_PERLHFieldSpecified;
            }
            set {
                this.nIL_PERLHFieldSpecified = value;
                this.RaisePropertyChanged("NIL_PERLHSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> ID_SATKER {
            get {
                return this.iD_SATKERField;
            }
            set {
                this.iD_SATKERField = value;
                this.RaisePropertyChanged("ID_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SATKERSpecified {
            get {
                return this.iD_SATKERFieldSpecified;
            }
            set {
                this.iD_SATKERFieldSpecified = value;
                this.RaisePropertyChanged("ID_SATKERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string TINGKAT_PERKARA_TK1 {
            get {
                return this.tINGKAT_PERKARA_TK1Field;
            }
            set {
                this.tINGKAT_PERKARA_TK1Field = value;
                this.RaisePropertyChanged("TINGKAT_PERKARA_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string JNS_PERKARA_TK1 {
            get {
                return this.jNS_PERKARA_TK1Field;
            }
            set {
                this.jNS_PERKARA_TK1Field = value;
                this.RaisePropertyChanged("JNS_PERKARA_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string NM_PENGADILAN_TK1 {
            get {
                return this.nM_PENGADILAN_TK1Field;
            }
            set {
                this.nM_PENGADILAN_TK1Field = value;
                this.RaisePropertyChanged("NM_PENGADILAN_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string NO_PERKARA_TK1NO_PERKARA {
            get {
                return this.nO_PERKARA_TK1NO_PERKARAField;
            }
            set {
                this.nO_PERKARA_TK1NO_PERKARAField = value;
                this.RaisePropertyChanged("NO_PERKARA_TK1NO_PERKARA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> TGL_SENGKETA_TK1 {
            get {
                return this.tGL_SENGKETA_TK1Field;
            }
            set {
                this.tGL_SENGKETA_TK1Field = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_SENGKETA_TK1Specified {
            get {
                return this.tGL_SENGKETA_TK1FieldSpecified;
            }
            set {
                this.tGL_SENGKETA_TK1FieldSpecified = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string PIHAK_PENGGUGAT_TK1 {
            get {
                return this.pIHAK_PENGGUGAT_TK1Field;
            }
            set {
                this.pIHAK_PENGGUGAT_TK1Field = value;
                this.RaisePropertyChanged("PIHAK_PENGGUGAT_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string PIHAK_TERGUGAT_TK1 {
            get {
                return this.pIHAK_TERGUGAT_TK1Field;
            }
            set {
                this.pIHAK_TERGUGAT_TK1Field = value;
                this.RaisePropertyChanged("PIHAK_TERGUGAT_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string AMAR_PUTUSAN_TK1 {
            get {
                return this.aMAR_PUTUSAN_TK1Field;
            }
            set {
                this.aMAR_PUTUSAN_TK1Field = value;
                this.RaisePropertyChanged("AMAR_PUTUSAN_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string POKOK_PERKARA_TK1 {
            get {
                return this.pOKOK_PERKARA_TK1Field;
            }
            set {
                this.pOKOK_PERKARA_TK1Field = value;
                this.RaisePropertyChanged("POKOK_PERKARA_TK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string TINGKAT_PERKARA_TK_TGI {
            get {
                return this.tINGKAT_PERKARA_TK_TGIField;
            }
            set {
                this.tINGKAT_PERKARA_TK_TGIField = value;
                this.RaisePropertyChanged("TINGKAT_PERKARA_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string JNS_PERKARA_TK_TGI {
            get {
                return this.jNS_PERKARA_TK_TGIField;
            }
            set {
                this.jNS_PERKARA_TK_TGIField = value;
                this.RaisePropertyChanged("JNS_PERKARA_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string NM_PENGADILAN_TK_TGI {
            get {
                return this.nM_PENGADILAN_TK_TGIField;
            }
            set {
                this.nM_PENGADILAN_TK_TGIField = value;
                this.RaisePropertyChanged("NM_PENGADILAN_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string NO_PERKARA_TK_TGI {
            get {
                return this.nO_PERKARA_TK_TGIField;
            }
            set {
                this.nO_PERKARA_TK_TGIField = value;
                this.RaisePropertyChanged("NO_PERKARA_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<System.DateTime> TGL_SENGKETA_TK_TGI {
            get {
                return this.tGL_SENGKETA_TK_TGIField;
            }
            set {
                this.tGL_SENGKETA_TK_TGIField = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_SENGKETA_TK_TGISpecified {
            get {
                return this.tGL_SENGKETA_TK_TGIFieldSpecified;
            }
            set {
                this.tGL_SENGKETA_TK_TGIFieldSpecified = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK_TGISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string PIHAK_PENGGUGAT_TK_TGI {
            get {
                return this.pIHAK_PENGGUGAT_TK_TGIField;
            }
            set {
                this.pIHAK_PENGGUGAT_TK_TGIField = value;
                this.RaisePropertyChanged("PIHAK_PENGGUGAT_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string PIHAK_TERGUGAT_TK_TGI {
            get {
                return this.pIHAK_TERGUGAT_TK_TGIField;
            }
            set {
                this.pIHAK_TERGUGAT_TK_TGIField = value;
                this.RaisePropertyChanged("PIHAK_TERGUGAT_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string AMAR_PUTUSAN_TK_TGI {
            get {
                return this.aMAR_PUTUSAN_TK_TGIField;
            }
            set {
                this.aMAR_PUTUSAN_TK_TGIField = value;
                this.RaisePropertyChanged("AMAR_PUTUSAN_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string POKOK_PERKARA_TK_TGI {
            get {
                return this.pOKOK_PERKARA_TK_TGIField;
            }
            set {
                this.pOKOK_PERKARA_TK_TGIField = value;
                this.RaisePropertyChanged("POKOK_PERKARA_TK_TGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string TINGKAT_PERKARA_TK_KSI {
            get {
                return this.tINGKAT_PERKARA_TK_KSIField;
            }
            set {
                this.tINGKAT_PERKARA_TK_KSIField = value;
                this.RaisePropertyChanged("TINGKAT_PERKARA_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string JNS_PERKARA_TK_KSI {
            get {
                return this.jNS_PERKARA_TK_KSIField;
            }
            set {
                this.jNS_PERKARA_TK_KSIField = value;
                this.RaisePropertyChanged("JNS_PERKARA_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string NM_PENGADILAN_TK_KSI {
            get {
                return this.nM_PENGADILAN_TK_KSIField;
            }
            set {
                this.nM_PENGADILAN_TK_KSIField = value;
                this.RaisePropertyChanged("NM_PENGADILAN_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string NO_PERKARA_TK_KSI {
            get {
                return this.nO_PERKARA_TK_KSIField;
            }
            set {
                this.nO_PERKARA_TK_KSIField = value;
                this.RaisePropertyChanged("NO_PERKARA_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<System.DateTime> TGL_SENGKETA_TK_KSI {
            get {
                return this.tGL_SENGKETA_TK_KSIField;
            }
            set {
                this.tGL_SENGKETA_TK_KSIField = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_SENGKETA_TK_KSISpecified {
            get {
                return this.tGL_SENGKETA_TK_KSIFieldSpecified;
            }
            set {
                this.tGL_SENGKETA_TK_KSIFieldSpecified = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK_KSISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string PIHAK_PENGGUGAT_TK_KSI {
            get {
                return this.pIHAK_PENGGUGAT_TK_KSIField;
            }
            set {
                this.pIHAK_PENGGUGAT_TK_KSIField = value;
                this.RaisePropertyChanged("PIHAK_PENGGUGAT_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string PIHAK_TERGUGAT_TK_KSI {
            get {
                return this.pIHAK_TERGUGAT_TK_KSIField;
            }
            set {
                this.pIHAK_TERGUGAT_TK_KSIField = value;
                this.RaisePropertyChanged("PIHAK_TERGUGAT_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string AMAR_PUTUSAN_TK_KSI {
            get {
                return this.aMAR_PUTUSAN_TK_KSIField;
            }
            set {
                this.aMAR_PUTUSAN_TK_KSIField = value;
                this.RaisePropertyChanged("AMAR_PUTUSAN_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string POKOK_PERKARA_TK_KSI {
            get {
                return this.pOKOK_PERKARA_TK_KSIField;
            }
            set {
                this.pOKOK_PERKARA_TK_KSIField = value;
                this.RaisePropertyChanged("POKOK_PERKARA_TK_KSI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string TINGKAT_PERKARA_TK_PK {
            get {
                return this.tINGKAT_PERKARA_TK_PKField;
            }
            set {
                this.tINGKAT_PERKARA_TK_PKField = value;
                this.RaisePropertyChanged("TINGKAT_PERKARA_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string JNS_PERKARA_TK_PK {
            get {
                return this.jNS_PERKARA_TK_PKField;
            }
            set {
                this.jNS_PERKARA_TK_PKField = value;
                this.RaisePropertyChanged("JNS_PERKARA_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public string NM_PENGADILAN_TK_PK {
            get {
                return this.nM_PENGADILAN_TK_PKField;
            }
            set {
                this.nM_PENGADILAN_TK_PKField = value;
                this.RaisePropertyChanged("NM_PENGADILAN_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string NO_PERKARA_TK_PK {
            get {
                return this.nO_PERKARA_TK_PKField;
            }
            set {
                this.nO_PERKARA_TK_PKField = value;
                this.RaisePropertyChanged("NO_PERKARA_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<System.DateTime> TGL_SENGKETA_TK_PK {
            get {
                return this.tGL_SENGKETA_TK_PKField;
            }
            set {
                this.tGL_SENGKETA_TK_PKField = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_SENGKETA_TK_PKSpecified {
            get {
                return this.tGL_SENGKETA_TK_PKFieldSpecified;
            }
            set {
                this.tGL_SENGKETA_TK_PKFieldSpecified = value;
                this.RaisePropertyChanged("TGL_SENGKETA_TK_PKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public string PIHAK_PENGGUGAT_TK_PK {
            get {
                return this.pIHAK_PENGGUGAT_TK_PKField;
            }
            set {
                this.pIHAK_PENGGUGAT_TK_PKField = value;
                this.RaisePropertyChanged("PIHAK_PENGGUGAT_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public string PIHAK_TERGUGAT_TK_PK {
            get {
                return this.pIHAK_TERGUGAT_TK_PKField;
            }
            set {
                this.pIHAK_TERGUGAT_TK_PKField = value;
                this.RaisePropertyChanged("PIHAK_TERGUGAT_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public string AMAR_PUTUSAN_TK_PK {
            get {
                return this.aMAR_PUTUSAN_TK_PKField;
            }
            set {
                this.aMAR_PUTUSAN_TK_PKField = value;
                this.RaisePropertyChanged("AMAR_PUTUSAN_TK_PK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string POKOK_PERKARA_TK_PK {
            get {
                return this.pOKOK_PERKARA_TK_PKField;
            }
            set {
                this.pOKOK_PERKARA_TK_PKField = value;
                this.RaisePropertyChanged("POKOK_PERKARA_TK_PK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_GUNA_KPKNL_B51")]
    public partial class OutputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WASDALSROW_MON_GUNA_KPKNL_B51[] sF_MON_GUNA_KPKNL_B51Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SF_MON_GUNA_KPKNL_B51_ITEM")]
        public WASDALSROW_MON_GUNA_KPKNL_B51[] SF_MON_GUNA_KPKNL_B51 {
            get {
                return this.sF_MON_GUNA_KPKNL_B51Field;
            }
            set {
                this.sF_MON_GUNA_KPKNL_B51Field = value;
                this.RaisePropertyChanged("SF_MON_GUNA_KPKNL_B51");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_GUNA_KPKNL_B51", Order=0)]
        public AppPengguna.SvcSelectGunaB51.InputParameters InputParameters;
        
        public executeRequest() {
        }
        
        public executeRequest(AppPengguna.SvcSelectGunaB51.InputParameters InputParameters) {
            this.InputParameters = InputParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_MON_GUNA_KPKNL_B51", Order=0)]
        public AppPengguna.SvcSelectGunaB51.OutputParameters OutputParameters;
        
        public executeResponse() {
        }
        
        public executeResponse(AppPengguna.SvcSelectGunaB51.OutputParameters OutputParameters) {
            this.OutputParameters = OutputParameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface execute_pttChannel : AppPengguna.SvcSelectGunaB51.execute_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class executeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public executeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppPengguna.SvcSelectGunaB51.OutputParameters Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppPengguna.SvcSelectGunaB51.OutputParameters)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class execute_pttClient : System.ServiceModel.ClientBase<AppPengguna.SvcSelectGunaB51.execute_ptt>, AppPengguna.SvcSelectGunaB51.execute_ptt {
        
        private BeginOperationDelegate onBeginexecuteDelegate;
        
        private EndOperationDelegate onEndexecuteDelegate;
        
        private System.Threading.SendOrPostCallback onexecuteCompletedDelegate;
        
        public execute_pttClient() {
        }
        
        public execute_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public execute_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<executeCompletedEventArgs> executeCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcSelectGunaB51.executeResponse AppPengguna.SvcSelectGunaB51.execute_ptt.execute(AppPengguna.SvcSelectGunaB51.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public AppPengguna.SvcSelectGunaB51.OutputParameters execute(AppPengguna.SvcSelectGunaB51.InputParameters InputParameters) {
            AppPengguna.SvcSelectGunaB51.executeRequest inValue = new AppPengguna.SvcSelectGunaB51.executeRequest();
            inValue.InputParameters = InputParameters;
            AppPengguna.SvcSelectGunaB51.executeResponse retVal = ((AppPengguna.SvcSelectGunaB51.execute_ptt)(this)).execute(inValue);
            return retVal.OutputParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppPengguna.SvcSelectGunaB51.execute_ptt.Beginexecute(AppPengguna.SvcSelectGunaB51.executeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginexecute(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginexecute(AppPengguna.SvcSelectGunaB51.InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcSelectGunaB51.executeRequest inValue = new AppPengguna.SvcSelectGunaB51.executeRequest();
            inValue.InputParameters = InputParameters;
            return ((AppPengguna.SvcSelectGunaB51.execute_ptt)(this)).Beginexecute(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcSelectGunaB51.executeResponse AppPengguna.SvcSelectGunaB51.execute_ptt.Endexecute(System.IAsyncResult result) {
            return base.Channel.Endexecute(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppPengguna.SvcSelectGunaB51.OutputParameters Endexecute(System.IAsyncResult result) {
            AppPengguna.SvcSelectGunaB51.executeResponse retVal = ((AppPengguna.SvcSelectGunaB51.execute_ptt)(this)).Endexecute(result);
            return retVal.OutputParameters;
        }
        
        private System.IAsyncResult OnBeginexecute(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcSelectGunaB51.InputParameters InputParameters = ((AppPengguna.SvcSelectGunaB51.InputParameters)(inValues[0]));
            return this.Beginexecute(InputParameters, callback, asyncState);
        }
        
        private object[] OnEndexecute(System.IAsyncResult result) {
            AppPengguna.SvcSelectGunaB51.OutputParameters retVal = this.Endexecute(result);
            return new object[] {
                    retVal};
        }
        
        private void OnexecuteCompleted(object state) {
            if ((this.executeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.executeCompleted(this, new executeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void executeAsync(AppPengguna.SvcSelectGunaB51.InputParameters InputParameters) {
            this.executeAsync(InputParameters, null);
        }
        
        public void executeAsync(AppPengguna.SvcSelectGunaB51.InputParameters InputParameters, object userState) {
            if ((this.onBeginexecuteDelegate == null)) {
                this.onBeginexecuteDelegate = new BeginOperationDelegate(this.OnBeginexecute);
            }
            if ((this.onEndexecuteDelegate == null)) {
                this.onEndexecuteDelegate = new EndOperationDelegate(this.OnEndexecute);
            }
            if ((this.onexecuteCompletedDelegate == null)) {
                this.onexecuteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnexecuteCompleted);
            }
            base.InvokeAsync(this.onBeginexecuteDelegate, new object[] {
                        InputParameters}, this.onEndexecuteDelegate, this.onexecuteCompletedDelegate, userState);
        }
    }
}
