//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPengguna.SvcWasdalLAINCrud {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oracle.com/sca/soapservice/siman_wasdal/wasdalOther/cud", ConfigurationName="SvcWasdalLAINCrud.call_ptt")]
    public interface call_ptt {
        
        // CODEGEN: Generating message contract since the operation execute is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppPengguna.SvcWasdalLAINCrud.executeResponse execute(AppPengguna.SvcWasdalLAINCrud.executeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="execute", ReplyAction="*")]
        System.IAsyncResult Beginexecute(AppPengguna.SvcWasdalLAINCrud.executeRequest request, System.AsyncCallback callback, object asyncState);
        
        AppPengguna.SvcWasdalLAINCrud.executeResponse Endexecute(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SP_SK_WASDAL_PSP_OTHER")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string p_SK_KEPUTUSANField;
        
        private string p_TGL_SKField;
        
        private System.Nullable<decimal> p_NILAI_PENETAPANField;
        
        private bool p_NILAI_PENETAPANFieldSpecified;
        
        private string p_URAIAN_KEPUTUSANField;
        
        private string p_IS_TBField;
        
        private string p_KD_PELAYANANField;
        
        private System.Nullable<decimal> p_ID_KPKNLField;
        
        private bool p_ID_KPKNLFieldSpecified;
        
        private System.Nullable<decimal> p_ID_USERField;
        
        private bool p_ID_USERFieldSpecified;
        
        private string p_KD_PENERBIT_SKField;
        
        private string p_NM_PENERBIT_SKField;
        
        private string p_TGL_CREATEDField;
        
        private string p_NIP_PENANDATANGANField;
        
        private string p_NM_PENANDATANGANField;
        
        private string p_JABATAN_TTDField;
        
        private string p_KD_PENERBIT_SK_DTLField;
        
        private string p_NM_PENERBIT_SK_DTLField;
        
        private System.Nullable<decimal> p_JANGKA_WAKTUField;
        
        private bool p_JANGKA_WAKTUFieldSpecified;
        
        private string p_PERUNTUKANField;
        
        private string p_KETERANGANField;
        
        private string p_PERIODEField;
        
        private System.Nullable<decimal> p_ID_PEMOHONField;
        
        private bool p_ID_PEMOHONFieldSpecified;
        
        private string p_TIPE_PEMOHONField;
        
        private string p_TIPE_PENGELOLAField;
        
        private string p_THN_ANGField;
        
        private string p_SELECTField;
        
        private string p_KD_KLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string P_SK_KEPUTUSAN {
            get {
                return this.p_SK_KEPUTUSANField;
            }
            set {
                this.p_SK_KEPUTUSANField = value;
                this.RaisePropertyChanged("P_SK_KEPUTUSAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string P_TGL_SK {
            get {
                return this.p_TGL_SKField;
            }
            set {
                this.p_TGL_SKField = value;
                this.RaisePropertyChanged("P_TGL_SK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> P_NILAI_PENETAPAN {
            get {
                return this.p_NILAI_PENETAPANField;
            }
            set {
                this.p_NILAI_PENETAPANField = value;
                this.RaisePropertyChanged("P_NILAI_PENETAPAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_NILAI_PENETAPANSpecified {
            get {
                return this.p_NILAI_PENETAPANFieldSpecified;
            }
            set {
                this.p_NILAI_PENETAPANFieldSpecified = value;
                this.RaisePropertyChanged("P_NILAI_PENETAPANSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string P_URAIAN_KEPUTUSAN {
            get {
                return this.p_URAIAN_KEPUTUSANField;
            }
            set {
                this.p_URAIAN_KEPUTUSANField = value;
                this.RaisePropertyChanged("P_URAIAN_KEPUTUSAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string P_IS_TB {
            get {
                return this.p_IS_TBField;
            }
            set {
                this.p_IS_TBField = value;
                this.RaisePropertyChanged("P_IS_TB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string P_KD_PELAYANAN {
            get {
                return this.p_KD_PELAYANANField;
            }
            set {
                this.p_KD_PELAYANANField = value;
                this.RaisePropertyChanged("P_KD_PELAYANAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> P_ID_KPKNL {
            get {
                return this.p_ID_KPKNLField;
            }
            set {
                this.p_ID_KPKNLField = value;
                this.RaisePropertyChanged("P_ID_KPKNL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ID_KPKNLSpecified {
            get {
                return this.p_ID_KPKNLFieldSpecified;
            }
            set {
                this.p_ID_KPKNLFieldSpecified = value;
                this.RaisePropertyChanged("P_ID_KPKNLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> P_ID_USER {
            get {
                return this.p_ID_USERField;
            }
            set {
                this.p_ID_USERField = value;
                this.RaisePropertyChanged("P_ID_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ID_USERSpecified {
            get {
                return this.p_ID_USERFieldSpecified;
            }
            set {
                this.p_ID_USERFieldSpecified = value;
                this.RaisePropertyChanged("P_ID_USERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string P_KD_PENERBIT_SK {
            get {
                return this.p_KD_PENERBIT_SKField;
            }
            set {
                this.p_KD_PENERBIT_SKField = value;
                this.RaisePropertyChanged("P_KD_PENERBIT_SK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string P_NM_PENERBIT_SK {
            get {
                return this.p_NM_PENERBIT_SKField;
            }
            set {
                this.p_NM_PENERBIT_SKField = value;
                this.RaisePropertyChanged("P_NM_PENERBIT_SK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string P_TGL_CREATED {
            get {
                return this.p_TGL_CREATEDField;
            }
            set {
                this.p_TGL_CREATEDField = value;
                this.RaisePropertyChanged("P_TGL_CREATED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string P_NIP_PENANDATANGAN {
            get {
                return this.p_NIP_PENANDATANGANField;
            }
            set {
                this.p_NIP_PENANDATANGANField = value;
                this.RaisePropertyChanged("P_NIP_PENANDATANGAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string P_NM_PENANDATANGAN {
            get {
                return this.p_NM_PENANDATANGANField;
            }
            set {
                this.p_NM_PENANDATANGANField = value;
                this.RaisePropertyChanged("P_NM_PENANDATANGAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string P_JABATAN_TTD {
            get {
                return this.p_JABATAN_TTDField;
            }
            set {
                this.p_JABATAN_TTDField = value;
                this.RaisePropertyChanged("P_JABATAN_TTD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string P_KD_PENERBIT_SK_DTL {
            get {
                return this.p_KD_PENERBIT_SK_DTLField;
            }
            set {
                this.p_KD_PENERBIT_SK_DTLField = value;
                this.RaisePropertyChanged("P_KD_PENERBIT_SK_DTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string P_NM_PENERBIT_SK_DTL {
            get {
                return this.p_NM_PENERBIT_SK_DTLField;
            }
            set {
                this.p_NM_PENERBIT_SK_DTLField = value;
                this.RaisePropertyChanged("P_NM_PENERBIT_SK_DTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<decimal> P_JANGKA_WAKTU {
            get {
                return this.p_JANGKA_WAKTUField;
            }
            set {
                this.p_JANGKA_WAKTUField = value;
                this.RaisePropertyChanged("P_JANGKA_WAKTU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_JANGKA_WAKTUSpecified {
            get {
                return this.p_JANGKA_WAKTUFieldSpecified;
            }
            set {
                this.p_JANGKA_WAKTUFieldSpecified = value;
                this.RaisePropertyChanged("P_JANGKA_WAKTUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string P_PERUNTUKAN {
            get {
                return this.p_PERUNTUKANField;
            }
            set {
                this.p_PERUNTUKANField = value;
                this.RaisePropertyChanged("P_PERUNTUKAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string P_KETERANGAN {
            get {
                return this.p_KETERANGANField;
            }
            set {
                this.p_KETERANGANField = value;
                this.RaisePropertyChanged("P_KETERANGAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string P_PERIODE {
            get {
                return this.p_PERIODEField;
            }
            set {
                this.p_PERIODEField = value;
                this.RaisePropertyChanged("P_PERIODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<decimal> P_ID_PEMOHON {
            get {
                return this.p_ID_PEMOHONField;
            }
            set {
                this.p_ID_PEMOHONField = value;
                this.RaisePropertyChanged("P_ID_PEMOHON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ID_PEMOHONSpecified {
            get {
                return this.p_ID_PEMOHONFieldSpecified;
            }
            set {
                this.p_ID_PEMOHONFieldSpecified = value;
                this.RaisePropertyChanged("P_ID_PEMOHONSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string P_TIPE_PEMOHON {
            get {
                return this.p_TIPE_PEMOHONField;
            }
            set {
                this.p_TIPE_PEMOHONField = value;
                this.RaisePropertyChanged("P_TIPE_PEMOHON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string P_TIPE_PENGELOLA {
            get {
                return this.p_TIPE_PENGELOLAField;
            }
            set {
                this.p_TIPE_PENGELOLAField = value;
                this.RaisePropertyChanged("P_TIPE_PENGELOLA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string P_THN_ANG {
            get {
                return this.p_THN_ANGField;
            }
            set {
                this.p_THN_ANGField = value;
                this.RaisePropertyChanged("P_THN_ANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string P_SELECT {
            get {
                return this.p_SELECTField;
            }
            set {
                this.p_SELECTField = value;
                this.RaisePropertyChanged("P_SELECT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string P_KD_KL {
            get {
                return this.p_KD_KLField;
            }
            set {
                this.p_KD_KLField = value;
                this.RaisePropertyChanged("P_KD_KL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SP_SK_WASDAL_PSP_OTHER")]
    public partial class OutputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pO_RESULTField;
        
        private string pO_RESULT_MESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string PO_RESULT {
            get {
                return this.pO_RESULTField;
            }
            set {
                this.pO_RESULTField = value;
                this.RaisePropertyChanged("PO_RESULT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string PO_RESULT_MESSAGE {
            get {
                return this.pO_RESULT_MESSAGEField;
            }
            set {
                this.pO_RESULT_MESSAGEField = value;
                this.RaisePropertyChanged("PO_RESULT_MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SP_SK_WASDAL_PSP_OTHER", Order=0)]
        public AppPengguna.SvcWasdalLAINCrud.InputParameters InputParameters;
        
        public executeRequest() {
        }
        
        public executeRequest(AppPengguna.SvcWasdalLAINCrud.InputParameters InputParameters) {
            this.InputParameters = InputParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SP_SK_WASDAL_PSP_OTHER", Order=0)]
        public AppPengguna.SvcWasdalLAINCrud.OutputParameters OutputParameters;
        
        public executeResponse() {
        }
        
        public executeResponse(AppPengguna.SvcWasdalLAINCrud.OutputParameters OutputParameters) {
            this.OutputParameters = OutputParameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface call_pttChannel : AppPengguna.SvcWasdalLAINCrud.call_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class executeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public executeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppPengguna.SvcWasdalLAINCrud.OutputParameters Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppPengguna.SvcWasdalLAINCrud.OutputParameters)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class call_pttClient : System.ServiceModel.ClientBase<AppPengguna.SvcWasdalLAINCrud.call_ptt>, AppPengguna.SvcWasdalLAINCrud.call_ptt {
        
        private BeginOperationDelegate onBeginexecuteDelegate;
        
        private EndOperationDelegate onEndexecuteDelegate;
        
        private System.Threading.SendOrPostCallback onexecuteCompletedDelegate;
        
        public call_pttClient() {
        }
        
        public call_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public call_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public call_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public call_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<executeCompletedEventArgs> executeCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcWasdalLAINCrud.executeResponse AppPengguna.SvcWasdalLAINCrud.call_ptt.execute(AppPengguna.SvcWasdalLAINCrud.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public AppPengguna.SvcWasdalLAINCrud.OutputParameters execute(AppPengguna.SvcWasdalLAINCrud.InputParameters InputParameters) {
            AppPengguna.SvcWasdalLAINCrud.executeRequest inValue = new AppPengguna.SvcWasdalLAINCrud.executeRequest();
            inValue.InputParameters = InputParameters;
            AppPengguna.SvcWasdalLAINCrud.executeResponse retVal = ((AppPengguna.SvcWasdalLAINCrud.call_ptt)(this)).execute(inValue);
            return retVal.OutputParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppPengguna.SvcWasdalLAINCrud.call_ptt.Beginexecute(AppPengguna.SvcWasdalLAINCrud.executeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginexecute(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginexecute(AppPengguna.SvcWasdalLAINCrud.InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcWasdalLAINCrud.executeRequest inValue = new AppPengguna.SvcWasdalLAINCrud.executeRequest();
            inValue.InputParameters = InputParameters;
            return ((AppPengguna.SvcWasdalLAINCrud.call_ptt)(this)).Beginexecute(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcWasdalLAINCrud.executeResponse AppPengguna.SvcWasdalLAINCrud.call_ptt.Endexecute(System.IAsyncResult result) {
            return base.Channel.Endexecute(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppPengguna.SvcWasdalLAINCrud.OutputParameters Endexecute(System.IAsyncResult result) {
            AppPengguna.SvcWasdalLAINCrud.executeResponse retVal = ((AppPengguna.SvcWasdalLAINCrud.call_ptt)(this)).Endexecute(result);
            return retVal.OutputParameters;
        }
        
        private System.IAsyncResult OnBeginexecute(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcWasdalLAINCrud.InputParameters InputParameters = ((AppPengguna.SvcWasdalLAINCrud.InputParameters)(inValues[0]));
            return this.Beginexecute(InputParameters, callback, asyncState);
        }
        
        private object[] OnEndexecute(System.IAsyncResult result) {
            AppPengguna.SvcWasdalLAINCrud.OutputParameters retVal = this.Endexecute(result);
            return new object[] {
                    retVal};
        }
        
        private void OnexecuteCompleted(object state) {
            if ((this.executeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.executeCompleted(this, new executeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void executeAsync(AppPengguna.SvcWasdalLAINCrud.InputParameters InputParameters) {
            this.executeAsync(InputParameters, null);
        }
        
        public void executeAsync(AppPengguna.SvcWasdalLAINCrud.InputParameters InputParameters, object userState) {
            if ((this.onBeginexecuteDelegate == null)) {
                this.onBeginexecuteDelegate = new BeginOperationDelegate(this.OnBeginexecute);
            }
            if ((this.onEndexecuteDelegate == null)) {
                this.onEndexecuteDelegate = new EndOperationDelegate(this.OnEndexecute);
            }
            if ((this.onexecuteCompletedDelegate == null)) {
                this.onexecuteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnexecuteCompleted);
            }
            base.InvokeAsync(this.onBeginexecuteDelegate, new object[] {
                        InputParameters}, this.onEndexecuteDelegate, this.onexecuteCompletedDelegate, userState);
        }
    }
}
