//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPengguna.SvcWasdalAsetSelect2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/wasdal/wasdal2018/SvcWasdalSelectAset2", ConfigurationName="SvcWasdalAsetSelect2.execute_ptt")]
    public interface execute_ptt {
        
        // CODEGEN: Generating message contract since the operation execute is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppPengguna.SvcWasdalAsetSelect2.executeResponse execute(AppPengguna.SvcWasdalAsetSelect2.executeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="execute", ReplyAction="*")]
        System.IAsyncResult Beginexecute(AppPengguna.SvcWasdalAsetSelect2.executeRequest request, System.AsyncCallback callback, object asyncState);
        
        AppPengguna.SvcWasdalAsetSelect2.executeResponse Endexecute(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_ROW_WASDAL_M_ASET2")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> p_MINField;
        
        private bool p_MINFieldSpecified;
        
        private System.Nullable<decimal> p_MAXField;
        
        private bool p_MAXFieldSpecified;
        
        private string p_COUNTField;
        
        private string sTR_WHEREField;
        
        private string p_COLField;
        
        private string p_SORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> P_MIN {
            get {
                return this.p_MINField;
            }
            set {
                this.p_MINField = value;
                this.RaisePropertyChanged("P_MIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MINSpecified {
            get {
                return this.p_MINFieldSpecified;
            }
            set {
                this.p_MINFieldSpecified = value;
                this.RaisePropertyChanged("P_MINSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> P_MAX {
            get {
                return this.p_MAXField;
            }
            set {
                this.p_MAXField = value;
                this.RaisePropertyChanged("P_MAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_MAXSpecified {
            get {
                return this.p_MAXFieldSpecified;
            }
            set {
                this.p_MAXFieldSpecified = value;
                this.RaisePropertyChanged("P_MAXSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string P_COUNT {
            get {
                return this.p_COUNTField;
            }
            set {
                this.p_COUNTField = value;
                this.RaisePropertyChanged("P_COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string STR_WHERE {
            get {
                return this.sTR_WHEREField;
            }
            set {
                this.sTR_WHEREField = value;
                this.RaisePropertyChanged("STR_WHERE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string P_COL {
            get {
                return this.p_COLField;
            }
            set {
                this.p_COLField = value;
                this.RaisePropertyChanged("P_COL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string P_SORT {
            get {
                return this.p_SORTField;
            }
            set {
                this.p_SORTField = value;
                this.RaisePropertyChanged("P_SORT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WASDAL.SROW_WASDAL_M_ASET2", Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_ROW_WASDAL_M_ASET2")]
    public partial class WASDALSROW_WASDAL_M_ASET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> nUMField;
        
        private bool nUMFieldSpecified;
        
        private System.Nullable<decimal> iD_ASETField;
        
        private bool iD_ASETFieldSpecified;
        
        private System.Nullable<decimal> kD_JNS_BMNField;
        
        private bool kD_JNS_BMNFieldSpecified;
        
        private string nM_JNS_BMNField;
        
        private System.Nullable<decimal> iD_SATKERField;
        
        private bool iD_SATKERFieldSpecified;
        
        private string uR_SATKERField;
        
        private string kD_SATKERField;
        
        private string kD_WILESELONField;
        
        private System.Nullable<decimal> iD_KANWILField;
        
        private bool iD_KANWILFieldSpecified;
        
        private string kD_KORWILField;
        
        private string kD_ESELONKLField;
        
        private string uR_WILField;
        
        private System.Nullable<decimal> iD_KORWILField;
        
        private bool iD_KORWILFieldSpecified;
        
        private System.Nullable<decimal> iD_ESELON1Field;
        
        private bool iD_ESELON1FieldSpecified;
        
        private string kD_ESELON1Field;
        
        private string kD_KLField;
        
        private string uR_ESELON1Field;
        
        private System.Nullable<decimal> iD_KLField;
        
        private bool iD_KLFieldSpecified;
        
        private string uR_KLField;
        
        private string kD_KANWILField;
        
        private string uR_KANWILField;
        
        private string kD_BRGField;
        
        private string kD_SKELBRGField;
        
        private string kD_SSKELField;
        
        private string sATUANField;
        
        private string uR_SSKELField;
        
        private string kD_PERKField;
        
        private string dASARField;
        
        private string kDPERKBRField;
        
        private string kD_KELBRGField;
        
        private string kD_SKELField;
        
        private string uR_SKELField;
        
        private string kD_KELField;
        
        private string kD_BIDBRGField;
        
        private string uR_KELField;
        
        private string kD_BIDField;
        
        private string kD_GOLField;
        
        private string uR_BIDField;
        
        private string uR_GOLField;
        
        private string kD_KONDISIField;
        
        private string uR_KONDISIField;
        
        private System.Nullable<decimal> nO_ASETField;
        
        private bool nO_ASETFieldSpecified;
        
        private string tHN_ANGField;
        
        private string pERIODEField;
        
        private string tERCATATField;
        
        private string uR_TERCATATField;
        
        private string kD_DSR_HRGField;
        
        private string uR_DSR_HRGField;
        
        private string kD_DATAField;
        
        private string uR_DATAField;
        
        private string fLAG_KORField;
        
        private string mERKField;
        
        private string tIPEField;
        
        private string kDBLUField;
        
        private string fLAG_TTPField;
        
        private string fLAG_KRMField;
        
        private string nOREGField;
        
        private string kDBAPELField;
        
        private string kDKPKNLField;
        
        private string uRKPKNLField;
        
        private System.Nullable<float> uMEKOField;
        
        private bool uMEKOFieldSpecified;
        
        private System.Nullable<decimal> rPH_RESField;
        
        private bool rPH_RESFieldSpecified;
        
        private string kDKPPNField;
        
        private string uRKPPNField;
        
        private string kD_STATUSField;
        
        private string uR_STATUSField;
        
        private string lOKASIField;
        
        private System.Nullable<decimal> rPH_ASETField;
        
        private bool rPH_ASETFieldSpecified;
        
        private System.Nullable<decimal> rPH_SUSUTField;
        
        private bool rPH_SUSUTFieldSpecified;
        
        private System.Nullable<decimal> rPH_MUTASIField;
        
        private bool rPH_MUTASIFieldSpecified;
        
        private System.Nullable<decimal> nILAI_SBLM_SUSUTField;
        
        private bool nILAI_SBLM_SUSUTFieldSpecified;
        
        private System.Nullable<decimal> nILAI_BUKUField;
        
        private bool nILAI_BUKUFieldSpecified;
        
        private System.Nullable<System.DateTime> tGL_REKAMField;
        
        private bool tGL_REKAMFieldSpecified;
        
        private System.Nullable<decimal> iD_PENGADAANField;
        
        private bool iD_PENGADAANFieldSpecified;
        
        private string nO_DANAField;
        
        private System.Nullable<System.DateTime> tGL_DANAField;
        
        private bool tGL_DANAFieldSpecified;
        
        private string dARIField;
        
        private string aSL_PERLHField;
        
        private System.Nullable<System.DateTime> tGL_PERLHField;
        
        private bool tGL_PERLHFieldSpecified;
        
        private string nO_SK_PERENCANAANField;
        
        private string kET_PENGADAANField;
        
        private string sTATUS_BMN_YNField;
        
        private System.Nullable<decimal> iD_BAS_KELField;
        
        private bool iD_BAS_KELFieldSpecified;
        
        private System.Nullable<decimal> iD_BASField;
        
        private bool iD_BASFieldSpecified;
        
        private string bPYBDS_YNField;
        
        private string fLAG_SAPField;
        
        private string sTATUS_KELOLAField;
        
        private string kD_PELAYANANField;
        
        private System.Nullable<decimal> iD_MUTASI_DTLField;
        
        private bool iD_MUTASI_DTLFieldSpecified;
        
        private System.Nullable<System.DateTime> tGL_BUKUField;
        
        private bool tGL_BUKUFieldSpecified;
        
        private string bLN_BUKUField;
        
        private string tHN_BUKUField;
        
        private System.Nullable<decimal> kUANTITASField;
        
        private bool kUANTITASFieldSpecified;
        
        private string iNTRA_EXTRAField;
        
        private string jNS_TRNField;
        
        private string uR_TRNField;
        
        private string kD_AKUNField;
        
        private string uR_AKUNField;
        
        private string nO_BUKTIField;
        
        private System.Nullable<decimal> nILAI_SATField;
        
        private bool nILAI_SATFieldSpecified;
        
        private string kD_SUMBER_DANAField;
        
        private string uR_SUMBER_DANAField;
        
        private System.Nullable<decimal> tOTAL_DATAField;
        
        private bool tOTAL_DATAFieldSpecified;
        
        private System.Nullable<decimal> sUM_RPH_ASETField;
        
        private bool sUM_RPH_ASETFieldSpecified;
        
        private System.Nullable<decimal> sUM_RPH_SUSUTField;
        
        private bool sUM_RPH_SUSUTFieldSpecified;
        
        private System.Nullable<decimal> sUM_RPH_MUTASIField;
        
        private bool sUM_RPH_MUTASIFieldSpecified;
        
        private string iN_KD_PELAYANANField;
        
        private string iN_NM_PELAYANANField;
        
        private System.Nullable<decimal> jML_PHOTOField;
        
        private bool jML_PHOTOFieldSpecified;
        
        private System.Nullable<decimal> iD_SATKER_PARENTField;
        
        private bool iD_SATKER_PARENTFieldSpecified;
        
        private string kETERANGANField;
        
        private string nO_DSR_MTSField;
        
        private System.Nullable<decimal> iD_KPKNLField;
        
        private bool iD_KPKNLFieldSpecified;
        
        private string nO_PSPField;
        
        private System.Nullable<System.DateTime> tGL_PSPField;
        
        private bool tGL_PSPFieldSpecified;
        
        private string tA_PSPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
                this.RaisePropertyChanged("NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUMSpecified {
            get {
                return this.nUMFieldSpecified;
            }
            set {
                this.nUMFieldSpecified = value;
                this.RaisePropertyChanged("NUMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> ID_ASET {
            get {
                return this.iD_ASETField;
            }
            set {
                this.iD_ASETField = value;
                this.RaisePropertyChanged("ID_ASET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_ASETSpecified {
            get {
                return this.iD_ASETFieldSpecified;
            }
            set {
                this.iD_ASETFieldSpecified = value;
                this.RaisePropertyChanged("ID_ASETSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> KD_JNS_BMN {
            get {
                return this.kD_JNS_BMNField;
            }
            set {
                this.kD_JNS_BMNField = value;
                this.RaisePropertyChanged("KD_JNS_BMN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KD_JNS_BMNSpecified {
            get {
                return this.kD_JNS_BMNFieldSpecified;
            }
            set {
                this.kD_JNS_BMNFieldSpecified = value;
                this.RaisePropertyChanged("KD_JNS_BMNSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string NM_JNS_BMN {
            get {
                return this.nM_JNS_BMNField;
            }
            set {
                this.nM_JNS_BMNField = value;
                this.RaisePropertyChanged("NM_JNS_BMN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> ID_SATKER {
            get {
                return this.iD_SATKERField;
            }
            set {
                this.iD_SATKERField = value;
                this.RaisePropertyChanged("ID_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SATKERSpecified {
            get {
                return this.iD_SATKERFieldSpecified;
            }
            set {
                this.iD_SATKERFieldSpecified = value;
                this.RaisePropertyChanged("ID_SATKERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string UR_SATKER {
            get {
                return this.uR_SATKERField;
            }
            set {
                this.uR_SATKERField = value;
                this.RaisePropertyChanged("UR_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string KD_SATKER {
            get {
                return this.kD_SATKERField;
            }
            set {
                this.kD_SATKERField = value;
                this.RaisePropertyChanged("KD_SATKER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string KD_WILESELON {
            get {
                return this.kD_WILESELONField;
            }
            set {
                this.kD_WILESELONField = value;
                this.RaisePropertyChanged("KD_WILESELON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> ID_KANWIL {
            get {
                return this.iD_KANWILField;
            }
            set {
                this.iD_KANWILField = value;
                this.RaisePropertyChanged("ID_KANWIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_KANWILSpecified {
            get {
                return this.iD_KANWILFieldSpecified;
            }
            set {
                this.iD_KANWILFieldSpecified = value;
                this.RaisePropertyChanged("ID_KANWILSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string KD_KORWIL {
            get {
                return this.kD_KORWILField;
            }
            set {
                this.kD_KORWILField = value;
                this.RaisePropertyChanged("KD_KORWIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string KD_ESELONKL {
            get {
                return this.kD_ESELONKLField;
            }
            set {
                this.kD_ESELONKLField = value;
                this.RaisePropertyChanged("KD_ESELONKL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string UR_WIL {
            get {
                return this.uR_WILField;
            }
            set {
                this.uR_WILField = value;
                this.RaisePropertyChanged("UR_WIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> ID_KORWIL {
            get {
                return this.iD_KORWILField;
            }
            set {
                this.iD_KORWILField = value;
                this.RaisePropertyChanged("ID_KORWIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_KORWILSpecified {
            get {
                return this.iD_KORWILFieldSpecified;
            }
            set {
                this.iD_KORWILFieldSpecified = value;
                this.RaisePropertyChanged("ID_KORWILSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> ID_ESELON1 {
            get {
                return this.iD_ESELON1Field;
            }
            set {
                this.iD_ESELON1Field = value;
                this.RaisePropertyChanged("ID_ESELON1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_ESELON1Specified {
            get {
                return this.iD_ESELON1FieldSpecified;
            }
            set {
                this.iD_ESELON1FieldSpecified = value;
                this.RaisePropertyChanged("ID_ESELON1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string KD_ESELON1 {
            get {
                return this.kD_ESELON1Field;
            }
            set {
                this.kD_ESELON1Field = value;
                this.RaisePropertyChanged("KD_ESELON1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string KD_KL {
            get {
                return this.kD_KLField;
            }
            set {
                this.kD_KLField = value;
                this.RaisePropertyChanged("KD_KL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string UR_ESELON1 {
            get {
                return this.uR_ESELON1Field;
            }
            set {
                this.uR_ESELON1Field = value;
                this.RaisePropertyChanged("UR_ESELON1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> ID_KL {
            get {
                return this.iD_KLField;
            }
            set {
                this.iD_KLField = value;
                this.RaisePropertyChanged("ID_KL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_KLSpecified {
            get {
                return this.iD_KLFieldSpecified;
            }
            set {
                this.iD_KLFieldSpecified = value;
                this.RaisePropertyChanged("ID_KLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string UR_KL {
            get {
                return this.uR_KLField;
            }
            set {
                this.uR_KLField = value;
                this.RaisePropertyChanged("UR_KL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string KD_KANWIL {
            get {
                return this.kD_KANWILField;
            }
            set {
                this.kD_KANWILField = value;
                this.RaisePropertyChanged("KD_KANWIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string UR_KANWIL {
            get {
                return this.uR_KANWILField;
            }
            set {
                this.uR_KANWILField = value;
                this.RaisePropertyChanged("UR_KANWIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string KD_BRG {
            get {
                return this.kD_BRGField;
            }
            set {
                this.kD_BRGField = value;
                this.RaisePropertyChanged("KD_BRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string KD_SKELBRG {
            get {
                return this.kD_SKELBRGField;
            }
            set {
                this.kD_SKELBRGField = value;
                this.RaisePropertyChanged("KD_SKELBRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string KD_SSKEL {
            get {
                return this.kD_SSKELField;
            }
            set {
                this.kD_SSKELField = value;
                this.RaisePropertyChanged("KD_SSKEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string SATUAN {
            get {
                return this.sATUANField;
            }
            set {
                this.sATUANField = value;
                this.RaisePropertyChanged("SATUAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string UR_SSKEL {
            get {
                return this.uR_SSKELField;
            }
            set {
                this.uR_SSKELField = value;
                this.RaisePropertyChanged("UR_SSKEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string KD_PERK {
            get {
                return this.kD_PERKField;
            }
            set {
                this.kD_PERKField = value;
                this.RaisePropertyChanged("KD_PERK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string DASAR {
            get {
                return this.dASARField;
            }
            set {
                this.dASARField = value;
                this.RaisePropertyChanged("DASAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string KDPERKBR {
            get {
                return this.kDPERKBRField;
            }
            set {
                this.kDPERKBRField = value;
                this.RaisePropertyChanged("KDPERKBR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string KD_KELBRG {
            get {
                return this.kD_KELBRGField;
            }
            set {
                this.kD_KELBRGField = value;
                this.RaisePropertyChanged("KD_KELBRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string KD_SKEL {
            get {
                return this.kD_SKELField;
            }
            set {
                this.kD_SKELField = value;
                this.RaisePropertyChanged("KD_SKEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string UR_SKEL {
            get {
                return this.uR_SKELField;
            }
            set {
                this.uR_SKELField = value;
                this.RaisePropertyChanged("UR_SKEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string KD_KEL {
            get {
                return this.kD_KELField;
            }
            set {
                this.kD_KELField = value;
                this.RaisePropertyChanged("KD_KEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string KD_BIDBRG {
            get {
                return this.kD_BIDBRGField;
            }
            set {
                this.kD_BIDBRGField = value;
                this.RaisePropertyChanged("KD_BIDBRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string UR_KEL {
            get {
                return this.uR_KELField;
            }
            set {
                this.uR_KELField = value;
                this.RaisePropertyChanged("UR_KEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string KD_BID {
            get {
                return this.kD_BIDField;
            }
            set {
                this.kD_BIDField = value;
                this.RaisePropertyChanged("KD_BID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string KD_GOL {
            get {
                return this.kD_GOLField;
            }
            set {
                this.kD_GOLField = value;
                this.RaisePropertyChanged("KD_GOL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string UR_BID {
            get {
                return this.uR_BIDField;
            }
            set {
                this.uR_BIDField = value;
                this.RaisePropertyChanged("UR_BID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public string UR_GOL {
            get {
                return this.uR_GOLField;
            }
            set {
                this.uR_GOLField = value;
                this.RaisePropertyChanged("UR_GOL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string KD_KONDISI {
            get {
                return this.kD_KONDISIField;
            }
            set {
                this.kD_KONDISIField = value;
                this.RaisePropertyChanged("KD_KONDISI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public string UR_KONDISI {
            get {
                return this.uR_KONDISIField;
            }
            set {
                this.uR_KONDISIField = value;
                this.RaisePropertyChanged("UR_KONDISI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<decimal> NO_ASET {
            get {
                return this.nO_ASETField;
            }
            set {
                this.nO_ASETField = value;
                this.RaisePropertyChanged("NO_ASET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NO_ASETSpecified {
            get {
                return this.nO_ASETFieldSpecified;
            }
            set {
                this.nO_ASETFieldSpecified = value;
                this.RaisePropertyChanged("NO_ASETSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public string THN_ANG {
            get {
                return this.tHN_ANGField;
            }
            set {
                this.tHN_ANGField = value;
                this.RaisePropertyChanged("THN_ANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public string PERIODE {
            get {
                return this.pERIODEField;
            }
            set {
                this.pERIODEField = value;
                this.RaisePropertyChanged("PERIODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string TERCATAT {
            get {
                return this.tERCATATField;
            }
            set {
                this.tERCATATField = value;
                this.RaisePropertyChanged("TERCATAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public string UR_TERCATAT {
            get {
                return this.uR_TERCATATField;
            }
            set {
                this.uR_TERCATATField = value;
                this.RaisePropertyChanged("UR_TERCATAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public string KD_DSR_HRG {
            get {
                return this.kD_DSR_HRGField;
            }
            set {
                this.kD_DSR_HRGField = value;
                this.RaisePropertyChanged("KD_DSR_HRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public string UR_DSR_HRG {
            get {
                return this.uR_DSR_HRGField;
            }
            set {
                this.uR_DSR_HRGField = value;
                this.RaisePropertyChanged("UR_DSR_HRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public string KD_DATA {
            get {
                return this.kD_DATAField;
            }
            set {
                this.kD_DATAField = value;
                this.RaisePropertyChanged("KD_DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public string UR_DATA {
            get {
                return this.uR_DATAField;
            }
            set {
                this.uR_DATAField = value;
                this.RaisePropertyChanged("UR_DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public string FLAG_KOR {
            get {
                return this.fLAG_KORField;
            }
            set {
                this.fLAG_KORField = value;
                this.RaisePropertyChanged("FLAG_KOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=51)]
        public string MERK {
            get {
                return this.mERKField;
            }
            set {
                this.mERKField = value;
                this.RaisePropertyChanged("MERK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public string TIPE {
            get {
                return this.tIPEField;
            }
            set {
                this.tIPEField = value;
                this.RaisePropertyChanged("TIPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=53)]
        public string KDBLU {
            get {
                return this.kDBLUField;
            }
            set {
                this.kDBLUField = value;
                this.RaisePropertyChanged("KDBLU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=54)]
        public string FLAG_TTP {
            get {
                return this.fLAG_TTPField;
            }
            set {
                this.fLAG_TTPField = value;
                this.RaisePropertyChanged("FLAG_TTP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=55)]
        public string FLAG_KRM {
            get {
                return this.fLAG_KRMField;
            }
            set {
                this.fLAG_KRMField = value;
                this.RaisePropertyChanged("FLAG_KRM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=56)]
        public string NOREG {
            get {
                return this.nOREGField;
            }
            set {
                this.nOREGField = value;
                this.RaisePropertyChanged("NOREG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=57)]
        public string KDBAPEL {
            get {
                return this.kDBAPELField;
            }
            set {
                this.kDBAPELField = value;
                this.RaisePropertyChanged("KDBAPEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=58)]
        public string KDKPKNL {
            get {
                return this.kDKPKNLField;
            }
            set {
                this.kDKPKNLField = value;
                this.RaisePropertyChanged("KDKPKNL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=59)]
        public string URKPKNL {
            get {
                return this.uRKPKNLField;
            }
            set {
                this.uRKPKNLField = value;
                this.RaisePropertyChanged("URKPKNL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=60)]
        public System.Nullable<float> UMEKO {
            get {
                return this.uMEKOField;
            }
            set {
                this.uMEKOField = value;
                this.RaisePropertyChanged("UMEKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UMEKOSpecified {
            get {
                return this.uMEKOFieldSpecified;
            }
            set {
                this.uMEKOFieldSpecified = value;
                this.RaisePropertyChanged("UMEKOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=61)]
        public System.Nullable<decimal> RPH_RES {
            get {
                return this.rPH_RESField;
            }
            set {
                this.rPH_RESField = value;
                this.RaisePropertyChanged("RPH_RES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RPH_RESSpecified {
            get {
                return this.rPH_RESFieldSpecified;
            }
            set {
                this.rPH_RESFieldSpecified = value;
                this.RaisePropertyChanged("RPH_RESSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=62)]
        public string KDKPPN {
            get {
                return this.kDKPPNField;
            }
            set {
                this.kDKPPNField = value;
                this.RaisePropertyChanged("KDKPPN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=63)]
        public string URKPPN {
            get {
                return this.uRKPPNField;
            }
            set {
                this.uRKPPNField = value;
                this.RaisePropertyChanged("URKPPN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=64)]
        public string KD_STATUS {
            get {
                return this.kD_STATUSField;
            }
            set {
                this.kD_STATUSField = value;
                this.RaisePropertyChanged("KD_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=65)]
        public string UR_STATUS {
            get {
                return this.uR_STATUSField;
            }
            set {
                this.uR_STATUSField = value;
                this.RaisePropertyChanged("UR_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=66)]
        public string LOKASI {
            get {
                return this.lOKASIField;
            }
            set {
                this.lOKASIField = value;
                this.RaisePropertyChanged("LOKASI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=67)]
        public System.Nullable<decimal> RPH_ASET {
            get {
                return this.rPH_ASETField;
            }
            set {
                this.rPH_ASETField = value;
                this.RaisePropertyChanged("RPH_ASET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RPH_ASETSpecified {
            get {
                return this.rPH_ASETFieldSpecified;
            }
            set {
                this.rPH_ASETFieldSpecified = value;
                this.RaisePropertyChanged("RPH_ASETSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=68)]
        public System.Nullable<decimal> RPH_SUSUT {
            get {
                return this.rPH_SUSUTField;
            }
            set {
                this.rPH_SUSUTField = value;
                this.RaisePropertyChanged("RPH_SUSUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RPH_SUSUTSpecified {
            get {
                return this.rPH_SUSUTFieldSpecified;
            }
            set {
                this.rPH_SUSUTFieldSpecified = value;
                this.RaisePropertyChanged("RPH_SUSUTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=69)]
        public System.Nullable<decimal> RPH_MUTASI {
            get {
                return this.rPH_MUTASIField;
            }
            set {
                this.rPH_MUTASIField = value;
                this.RaisePropertyChanged("RPH_MUTASI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RPH_MUTASISpecified {
            get {
                return this.rPH_MUTASIFieldSpecified;
            }
            set {
                this.rPH_MUTASIFieldSpecified = value;
                this.RaisePropertyChanged("RPH_MUTASISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=70)]
        public System.Nullable<decimal> NILAI_SBLM_SUSUT {
            get {
                return this.nILAI_SBLM_SUSUTField;
            }
            set {
                this.nILAI_SBLM_SUSUTField = value;
                this.RaisePropertyChanged("NILAI_SBLM_SUSUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NILAI_SBLM_SUSUTSpecified {
            get {
                return this.nILAI_SBLM_SUSUTFieldSpecified;
            }
            set {
                this.nILAI_SBLM_SUSUTFieldSpecified = value;
                this.RaisePropertyChanged("NILAI_SBLM_SUSUTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=71)]
        public System.Nullable<decimal> NILAI_BUKU {
            get {
                return this.nILAI_BUKUField;
            }
            set {
                this.nILAI_BUKUField = value;
                this.RaisePropertyChanged("NILAI_BUKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NILAI_BUKUSpecified {
            get {
                return this.nILAI_BUKUFieldSpecified;
            }
            set {
                this.nILAI_BUKUFieldSpecified = value;
                this.RaisePropertyChanged("NILAI_BUKUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=72)]
        public System.Nullable<System.DateTime> TGL_REKAM {
            get {
                return this.tGL_REKAMField;
            }
            set {
                this.tGL_REKAMField = value;
                this.RaisePropertyChanged("TGL_REKAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_REKAMSpecified {
            get {
                return this.tGL_REKAMFieldSpecified;
            }
            set {
                this.tGL_REKAMFieldSpecified = value;
                this.RaisePropertyChanged("TGL_REKAMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=73)]
        public System.Nullable<decimal> ID_PENGADAAN {
            get {
                return this.iD_PENGADAANField;
            }
            set {
                this.iD_PENGADAANField = value;
                this.RaisePropertyChanged("ID_PENGADAAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_PENGADAANSpecified {
            get {
                return this.iD_PENGADAANFieldSpecified;
            }
            set {
                this.iD_PENGADAANFieldSpecified = value;
                this.RaisePropertyChanged("ID_PENGADAANSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=74)]
        public string NO_DANA {
            get {
                return this.nO_DANAField;
            }
            set {
                this.nO_DANAField = value;
                this.RaisePropertyChanged("NO_DANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=75)]
        public System.Nullable<System.DateTime> TGL_DANA {
            get {
                return this.tGL_DANAField;
            }
            set {
                this.tGL_DANAField = value;
                this.RaisePropertyChanged("TGL_DANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_DANASpecified {
            get {
                return this.tGL_DANAFieldSpecified;
            }
            set {
                this.tGL_DANAFieldSpecified = value;
                this.RaisePropertyChanged("TGL_DANASpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=76)]
        public string DARI {
            get {
                return this.dARIField;
            }
            set {
                this.dARIField = value;
                this.RaisePropertyChanged("DARI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=77)]
        public string ASL_PERLH {
            get {
                return this.aSL_PERLHField;
            }
            set {
                this.aSL_PERLHField = value;
                this.RaisePropertyChanged("ASL_PERLH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=78)]
        public System.Nullable<System.DateTime> TGL_PERLH {
            get {
                return this.tGL_PERLHField;
            }
            set {
                this.tGL_PERLHField = value;
                this.RaisePropertyChanged("TGL_PERLH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_PERLHSpecified {
            get {
                return this.tGL_PERLHFieldSpecified;
            }
            set {
                this.tGL_PERLHFieldSpecified = value;
                this.RaisePropertyChanged("TGL_PERLHSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=79)]
        public string NO_SK_PERENCANAAN {
            get {
                return this.nO_SK_PERENCANAANField;
            }
            set {
                this.nO_SK_PERENCANAANField = value;
                this.RaisePropertyChanged("NO_SK_PERENCANAAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=80)]
        public string KET_PENGADAAN {
            get {
                return this.kET_PENGADAANField;
            }
            set {
                this.kET_PENGADAANField = value;
                this.RaisePropertyChanged("KET_PENGADAAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=81)]
        public string STATUS_BMN_YN {
            get {
                return this.sTATUS_BMN_YNField;
            }
            set {
                this.sTATUS_BMN_YNField = value;
                this.RaisePropertyChanged("STATUS_BMN_YN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=82)]
        public System.Nullable<decimal> ID_BAS_KEL {
            get {
                return this.iD_BAS_KELField;
            }
            set {
                this.iD_BAS_KELField = value;
                this.RaisePropertyChanged("ID_BAS_KEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_BAS_KELSpecified {
            get {
                return this.iD_BAS_KELFieldSpecified;
            }
            set {
                this.iD_BAS_KELFieldSpecified = value;
                this.RaisePropertyChanged("ID_BAS_KELSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=83)]
        public System.Nullable<decimal> ID_BAS {
            get {
                return this.iD_BASField;
            }
            set {
                this.iD_BASField = value;
                this.RaisePropertyChanged("ID_BAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_BASSpecified {
            get {
                return this.iD_BASFieldSpecified;
            }
            set {
                this.iD_BASFieldSpecified = value;
                this.RaisePropertyChanged("ID_BASSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=84)]
        public string BPYBDS_YN {
            get {
                return this.bPYBDS_YNField;
            }
            set {
                this.bPYBDS_YNField = value;
                this.RaisePropertyChanged("BPYBDS_YN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=85)]
        public string FLAG_SAP {
            get {
                return this.fLAG_SAPField;
            }
            set {
                this.fLAG_SAPField = value;
                this.RaisePropertyChanged("FLAG_SAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=86)]
        public string STATUS_KELOLA {
            get {
                return this.sTATUS_KELOLAField;
            }
            set {
                this.sTATUS_KELOLAField = value;
                this.RaisePropertyChanged("STATUS_KELOLA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=87)]
        public string KD_PELAYANAN {
            get {
                return this.kD_PELAYANANField;
            }
            set {
                this.kD_PELAYANANField = value;
                this.RaisePropertyChanged("KD_PELAYANAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=88)]
        public System.Nullable<decimal> ID_MUTASI_DTL {
            get {
                return this.iD_MUTASI_DTLField;
            }
            set {
                this.iD_MUTASI_DTLField = value;
                this.RaisePropertyChanged("ID_MUTASI_DTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_MUTASI_DTLSpecified {
            get {
                return this.iD_MUTASI_DTLFieldSpecified;
            }
            set {
                this.iD_MUTASI_DTLFieldSpecified = value;
                this.RaisePropertyChanged("ID_MUTASI_DTLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=89)]
        public System.Nullable<System.DateTime> TGL_BUKU {
            get {
                return this.tGL_BUKUField;
            }
            set {
                this.tGL_BUKUField = value;
                this.RaisePropertyChanged("TGL_BUKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_BUKUSpecified {
            get {
                return this.tGL_BUKUFieldSpecified;
            }
            set {
                this.tGL_BUKUFieldSpecified = value;
                this.RaisePropertyChanged("TGL_BUKUSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=90)]
        public string BLN_BUKU {
            get {
                return this.bLN_BUKUField;
            }
            set {
                this.bLN_BUKUField = value;
                this.RaisePropertyChanged("BLN_BUKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=91)]
        public string THN_BUKU {
            get {
                return this.tHN_BUKUField;
            }
            set {
                this.tHN_BUKUField = value;
                this.RaisePropertyChanged("THN_BUKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=92)]
        public System.Nullable<decimal> KUANTITAS {
            get {
                return this.kUANTITASField;
            }
            set {
                this.kUANTITASField = value;
                this.RaisePropertyChanged("KUANTITAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KUANTITASSpecified {
            get {
                return this.kUANTITASFieldSpecified;
            }
            set {
                this.kUANTITASFieldSpecified = value;
                this.RaisePropertyChanged("KUANTITASSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=93)]
        public string INTRA_EXTRA {
            get {
                return this.iNTRA_EXTRAField;
            }
            set {
                this.iNTRA_EXTRAField = value;
                this.RaisePropertyChanged("INTRA_EXTRA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=94)]
        public string JNS_TRN {
            get {
                return this.jNS_TRNField;
            }
            set {
                this.jNS_TRNField = value;
                this.RaisePropertyChanged("JNS_TRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=95)]
        public string UR_TRN {
            get {
                return this.uR_TRNField;
            }
            set {
                this.uR_TRNField = value;
                this.RaisePropertyChanged("UR_TRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=96)]
        public string KD_AKUN {
            get {
                return this.kD_AKUNField;
            }
            set {
                this.kD_AKUNField = value;
                this.RaisePropertyChanged("KD_AKUN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=97)]
        public string UR_AKUN {
            get {
                return this.uR_AKUNField;
            }
            set {
                this.uR_AKUNField = value;
                this.RaisePropertyChanged("UR_AKUN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=98)]
        public string NO_BUKTI {
            get {
                return this.nO_BUKTIField;
            }
            set {
                this.nO_BUKTIField = value;
                this.RaisePropertyChanged("NO_BUKTI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=99)]
        public System.Nullable<decimal> NILAI_SAT {
            get {
                return this.nILAI_SATField;
            }
            set {
                this.nILAI_SATField = value;
                this.RaisePropertyChanged("NILAI_SAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NILAI_SATSpecified {
            get {
                return this.nILAI_SATFieldSpecified;
            }
            set {
                this.nILAI_SATFieldSpecified = value;
                this.RaisePropertyChanged("NILAI_SATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=100)]
        public string KD_SUMBER_DANA {
            get {
                return this.kD_SUMBER_DANAField;
            }
            set {
                this.kD_SUMBER_DANAField = value;
                this.RaisePropertyChanged("KD_SUMBER_DANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=101)]
        public string UR_SUMBER_DANA {
            get {
                return this.uR_SUMBER_DANAField;
            }
            set {
                this.uR_SUMBER_DANAField = value;
                this.RaisePropertyChanged("UR_SUMBER_DANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=102)]
        public System.Nullable<decimal> TOTAL_DATA {
            get {
                return this.tOTAL_DATAField;
            }
            set {
                this.tOTAL_DATAField = value;
                this.RaisePropertyChanged("TOTAL_DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TOTAL_DATASpecified {
            get {
                return this.tOTAL_DATAFieldSpecified;
            }
            set {
                this.tOTAL_DATAFieldSpecified = value;
                this.RaisePropertyChanged("TOTAL_DATASpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=103)]
        public System.Nullable<decimal> SUM_RPH_ASET {
            get {
                return this.sUM_RPH_ASETField;
            }
            set {
                this.sUM_RPH_ASETField = value;
                this.RaisePropertyChanged("SUM_RPH_ASET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUM_RPH_ASETSpecified {
            get {
                return this.sUM_RPH_ASETFieldSpecified;
            }
            set {
                this.sUM_RPH_ASETFieldSpecified = value;
                this.RaisePropertyChanged("SUM_RPH_ASETSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=104)]
        public System.Nullable<decimal> SUM_RPH_SUSUT {
            get {
                return this.sUM_RPH_SUSUTField;
            }
            set {
                this.sUM_RPH_SUSUTField = value;
                this.RaisePropertyChanged("SUM_RPH_SUSUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUM_RPH_SUSUTSpecified {
            get {
                return this.sUM_RPH_SUSUTFieldSpecified;
            }
            set {
                this.sUM_RPH_SUSUTFieldSpecified = value;
                this.RaisePropertyChanged("SUM_RPH_SUSUTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=105)]
        public System.Nullable<decimal> SUM_RPH_MUTASI {
            get {
                return this.sUM_RPH_MUTASIField;
            }
            set {
                this.sUM_RPH_MUTASIField = value;
                this.RaisePropertyChanged("SUM_RPH_MUTASI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUM_RPH_MUTASISpecified {
            get {
                return this.sUM_RPH_MUTASIFieldSpecified;
            }
            set {
                this.sUM_RPH_MUTASIFieldSpecified = value;
                this.RaisePropertyChanged("SUM_RPH_MUTASISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=106)]
        public string IN_KD_PELAYANAN {
            get {
                return this.iN_KD_PELAYANANField;
            }
            set {
                this.iN_KD_PELAYANANField = value;
                this.RaisePropertyChanged("IN_KD_PELAYANAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=107)]
        public string IN_NM_PELAYANAN {
            get {
                return this.iN_NM_PELAYANANField;
            }
            set {
                this.iN_NM_PELAYANANField = value;
                this.RaisePropertyChanged("IN_NM_PELAYANAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=108)]
        public System.Nullable<decimal> JML_PHOTO {
            get {
                return this.jML_PHOTOField;
            }
            set {
                this.jML_PHOTOField = value;
                this.RaisePropertyChanged("JML_PHOTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JML_PHOTOSpecified {
            get {
                return this.jML_PHOTOFieldSpecified;
            }
            set {
                this.jML_PHOTOFieldSpecified = value;
                this.RaisePropertyChanged("JML_PHOTOSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=109)]
        public System.Nullable<decimal> ID_SATKER_PARENT {
            get {
                return this.iD_SATKER_PARENTField;
            }
            set {
                this.iD_SATKER_PARENTField = value;
                this.RaisePropertyChanged("ID_SATKER_PARENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_SATKER_PARENTSpecified {
            get {
                return this.iD_SATKER_PARENTFieldSpecified;
            }
            set {
                this.iD_SATKER_PARENTFieldSpecified = value;
                this.RaisePropertyChanged("ID_SATKER_PARENTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=110)]
        public string KETERANGAN {
            get {
                return this.kETERANGANField;
            }
            set {
                this.kETERANGANField = value;
                this.RaisePropertyChanged("KETERANGAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=111)]
        public string NO_DSR_MTS {
            get {
                return this.nO_DSR_MTSField;
            }
            set {
                this.nO_DSR_MTSField = value;
                this.RaisePropertyChanged("NO_DSR_MTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=112)]
        public System.Nullable<decimal> ID_KPKNL {
            get {
                return this.iD_KPKNLField;
            }
            set {
                this.iD_KPKNLField = value;
                this.RaisePropertyChanged("ID_KPKNL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ID_KPKNLSpecified {
            get {
                return this.iD_KPKNLFieldSpecified;
            }
            set {
                this.iD_KPKNLFieldSpecified = value;
                this.RaisePropertyChanged("ID_KPKNLSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=113)]
        public string NO_PSP {
            get {
                return this.nO_PSPField;
            }
            set {
                this.nO_PSPField = value;
                this.RaisePropertyChanged("NO_PSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=114)]
        public System.Nullable<System.DateTime> TGL_PSP {
            get {
                return this.tGL_PSPField;
            }
            set {
                this.tGL_PSPField = value;
                this.RaisePropertyChanged("TGL_PSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TGL_PSPSpecified {
            get {
                return this.tGL_PSPFieldSpecified;
            }
            set {
                this.tGL_PSPFieldSpecified = value;
                this.RaisePropertyChanged("TGL_PSPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=115)]
        public string TA_PSP {
            get {
                return this.tA_PSPField;
            }
            set {
                this.tA_PSPField = value;
                this.RaisePropertyChanged("TA_PSP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_ROW_WASDAL_M_ASET2")]
    public partial class OutputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WASDALSROW_WASDAL_M_ASET2[] sF_ROW_WASDAL_M_ASET2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SF_ROW_WASDAL_M_ASET2_ITEM")]
        public WASDALSROW_WASDAL_M_ASET2[] SF_ROW_WASDAL_M_ASET2 {
            get {
                return this.sF_ROW_WASDAL_M_ASET2Field;
            }
            set {
                this.sF_ROW_WASDAL_M_ASET2Field = value;
                this.RaisePropertyChanged("SF_ROW_WASDAL_M_ASET2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_ROW_WASDAL_M_ASET2", Order=0)]
        public AppPengguna.SvcWasdalAsetSelect2.InputParameters InputParameters;
        
        public executeRequest() {
        }
        
        public executeRequest(AppPengguna.SvcWasdalAsetSelect2.InputParameters InputParameters) {
            this.InputParameters = InputParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SF_ROW_WASDAL_M_ASET2", Order=0)]
        public AppPengguna.SvcWasdalAsetSelect2.OutputParameters OutputParameters;
        
        public executeResponse() {
        }
        
        public executeResponse(AppPengguna.SvcWasdalAsetSelect2.OutputParameters OutputParameters) {
            this.OutputParameters = OutputParameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface execute_pttChannel : AppPengguna.SvcWasdalAsetSelect2.execute_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class executeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public executeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppPengguna.SvcWasdalAsetSelect2.OutputParameters Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppPengguna.SvcWasdalAsetSelect2.OutputParameters)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class execute_pttClient : System.ServiceModel.ClientBase<AppPengguna.SvcWasdalAsetSelect2.execute_ptt>, AppPengguna.SvcWasdalAsetSelect2.execute_ptt {
        
        private BeginOperationDelegate onBeginexecuteDelegate;
        
        private EndOperationDelegate onEndexecuteDelegate;
        
        private System.Threading.SendOrPostCallback onexecuteCompletedDelegate;
        
        public execute_pttClient() {
        }
        
        public execute_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public execute_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public execute_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<executeCompletedEventArgs> executeCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcWasdalAsetSelect2.executeResponse AppPengguna.SvcWasdalAsetSelect2.execute_ptt.execute(AppPengguna.SvcWasdalAsetSelect2.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public AppPengguna.SvcWasdalAsetSelect2.OutputParameters execute(AppPengguna.SvcWasdalAsetSelect2.InputParameters InputParameters) {
            AppPengguna.SvcWasdalAsetSelect2.executeRequest inValue = new AppPengguna.SvcWasdalAsetSelect2.executeRequest();
            inValue.InputParameters = InputParameters;
            AppPengguna.SvcWasdalAsetSelect2.executeResponse retVal = ((AppPengguna.SvcWasdalAsetSelect2.execute_ptt)(this)).execute(inValue);
            return retVal.OutputParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppPengguna.SvcWasdalAsetSelect2.execute_ptt.Beginexecute(AppPengguna.SvcWasdalAsetSelect2.executeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginexecute(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginexecute(AppPengguna.SvcWasdalAsetSelect2.InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcWasdalAsetSelect2.executeRequest inValue = new AppPengguna.SvcWasdalAsetSelect2.executeRequest();
            inValue.InputParameters = InputParameters;
            return ((AppPengguna.SvcWasdalAsetSelect2.execute_ptt)(this)).Beginexecute(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppPengguna.SvcWasdalAsetSelect2.executeResponse AppPengguna.SvcWasdalAsetSelect2.execute_ptt.Endexecute(System.IAsyncResult result) {
            return base.Channel.Endexecute(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AppPengguna.SvcWasdalAsetSelect2.OutputParameters Endexecute(System.IAsyncResult result) {
            AppPengguna.SvcWasdalAsetSelect2.executeResponse retVal = ((AppPengguna.SvcWasdalAsetSelect2.execute_ptt)(this)).Endexecute(result);
            return retVal.OutputParameters;
        }
        
        private System.IAsyncResult OnBeginexecute(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppPengguna.SvcWasdalAsetSelect2.InputParameters InputParameters = ((AppPengguna.SvcWasdalAsetSelect2.InputParameters)(inValues[0]));
            return this.Beginexecute(InputParameters, callback, asyncState);
        }
        
        private object[] OnEndexecute(System.IAsyncResult result) {
            AppPengguna.SvcWasdalAsetSelect2.OutputParameters retVal = this.Endexecute(result);
            return new object[] {
                    retVal};
        }
        
        private void OnexecuteCompleted(object state) {
            if ((this.executeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.executeCompleted(this, new executeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void executeAsync(AppPengguna.SvcWasdalAsetSelect2.InputParameters InputParameters) {
            this.executeAsync(InputParameters, null);
        }
        
        public void executeAsync(AppPengguna.SvcWasdalAsetSelect2.InputParameters InputParameters, object userState) {
            if ((this.onBeginexecuteDelegate == null)) {
                this.onBeginexecuteDelegate = new BeginOperationDelegate(this.OnBeginexecute);
            }
            if ((this.onEndexecuteDelegate == null)) {
                this.onEndexecuteDelegate = new EndOperationDelegate(this.OnEndexecute);
            }
            if ((this.onexecuteCompletedDelegate == null)) {
                this.onexecuteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnexecuteCompleted);
            }
            base.InvokeAsync(this.onBeginexecuteDelegate, new object[] {
                        InputParameters}, this.onEndexecuteDelegate, this.onexecuteCompletedDelegate, userState);
        }
    }
}
